### ISSUE TITLE
Bug Report: it says it couldnt find visual studio 2017, and its missing HXCPP_VARS

### ISSUE THREAD

**Issue by NjokaOffical** [KadeDev/Funkin#2250]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.
![Screenshot (62)](https://user-images.githubusercontent.com/90661891/133177925-7c76e98d-8b68-431d-8aeb-ec2561f4135f.png)

**Comment by EliteMasterEric** [comment]
You need to install Visual Studio 2017 in order to build the game on Windows:

https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md#windows-only-dependencies-only-for-building-to-windows-building-html5-on-windows-does-not-require-this

**Comment by Hythrex** [comment]
> You need to install Visual Studio 2017 in order to build the game on Windows:
> 
> https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md#windows-only-dependencies-only-for-building-to-windows-building-html5-on-windows-does-not-require-this
1. If this worked, please close this.
2. Please read building.md before trying to compile
