### ISSUE TITLE
Bug Report: when i go to  latest development build (macOS) it just says access denied

### ISSUE THREAD

**Issue by WaterCoded** [KadeDev/Funkin#2251]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.

latest version

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

no

## Please describe your issue. Provide extensive detail and images if possible.

![IMG_4380](https://user-images.githubusercontent.com/90663404/133180961-acfc187f-fb1d-439a-8ae4-14c7c89ce4f9.png)

when i got to get the latest version for mac, it just says project not found or access denied

**Comment by WaterCoded** [comment]
not sure why the picture is a small square

**Comment by isakube** [comment]
when the github CI makes the .app, the Unix executable isn't a Unix executable. It's an extensionless text file instead. There's a command for fixing this but I can't remember what it is
