### ISSUE TITLE
better explanation of modcharts

### ISSUE THREAD

**Issue by TyricSatyric** [KadeDev/Funkin#2262]
## What is your suggestion, and why should it be implemented?
in the pages of modcharts i dont understand nothing:
![imagen_2021-09-15_160932](https://user-images.githubusercontent.com/63313393/133449057-b1f5638a-7ca0-4f64-a3bd-561b81205597.png)
So i think that we need a better explanation

**Comment by isakube** [comment]
skill issue :troll:
