### ISSUE TITLE
Bug Report: Slowing down songs makes them end early

### ISSUE THREAD

**Issue by Neptune-Sky** [KadeDev/Funkin#2266]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.

0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Lower song speed to below 1.0

## Please describe your issue. Provide extensive detail and images if possible.

If song speed is lower than 1.0, the song will stop at the percent of the speed value rather than the end of the song, for example speed of 0.5x makes the song end after it is halfway through

**Comment by somefnfplayerlol** [comment]
do not relay the base game's version
