### ISSUE TITLE
Base game crashed while loading

### ISSUE THREAD

**Issue by Shnitzelator** [KadeDev/Funkin#2271]
Sorry if this is a duplicate, I couldn't find someone with this problem

Im using Windows x64

Can't say which game version I'm using cuz the game won't load

I don't know where I messed up in my installation but the game can start, it just crashes at 20/21 on the loading screen (something I did weird is that I downloaded my MSVC and SDK after trying to load the game... I might have broke something)

No matter how I open the game (either by powershell or with the exe it created) it crashes before going to the main menu, I didn't add anything or changed anything in the files, I just have the base build of the kade engine and it's probably not an old version since I downloaded it today. The game crashes at 20/21 while loading and powershell doesn't detect any errors.

If someone can help me or think they can help with my problem please leave a message because I didn't find any post talking about an issue like this...

**Comment by YsoFurro** [comment]
i'm with the same issue, running the "lime test windows" code again i noted something that seems to be an error, but htat don't stop the compiling

`FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

did you noted that with you too?

**Comment by Shnitzelator** [comment]
Yeah, I have that too, now that you mention it, it seems a little off indeed

**Comment by Droma64** [comment]
I have the same problem, i don´t know what to do

**Comment by LevaRiikas** [comment]
I know Tutorial and Offsettest have mp3 files instead of ogg files, and that causes a basic crash. But even after fixing it seems KE crashes again, calling out for a "Null Object Reference"? It makes no sense, honestly.

**Comment by YsoFurro** [comment]
One thin i think it's worth mentionin, is that i have the 1.4.2 and 1.5.2 versions here to, this 2 were functioning well until i decided dowload the things for 1.7, after i download all that need to 1.7, the 1.4.2 and 1.5.2 also stoped working, baybe that is a problem with versions of the libraries you need to download?

**Comment by OtasGamer64** [comment]
I am experiencing this as well. Any solution?
