### ISSUE TITLE
kade engine 1.7 please tell me how to fix  C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll bug 

### ISSUE THREAD

**Issue by vaasans** [KadeDev/Funkin#2272]
please tell me how to fix  C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll bug and Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by somefnfplayerlol** [comment]
do in order:
```
haxelib remove extension-webm
haxelib git extension-webm https://github.com/KadeDev/extension-webm
lime rebuild extension-webm
```

**Comment by vaasans** [comment]
did not work

**Comment by somefnfplayerlol** [comment]
did you install visual studio 2017?

**Comment by vaasans** [comment]
yes

**Comment by EliteMasterEric** [comment]
`Error: Could not automatically setup MSVC`

This line indicates that you did not properly install all the tools required to run Visual Studio 2017, that the game needs to build. Please reread the build guide, paying special attention to the Building for Windows section, and try again.

**Comment by vaasans** [comment]
did not work
