### ISSUE TITLE
Bug Report: When loading the third song, it crashes without giving any error messages

### ISSUE THREAD

**Issue by MrBxcx** [KadeDev/Funkin#2273]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
64
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4 EK Kade Engine
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No I haven't, I didn't know what was the bug since it crashes without giving error messages
## Please describe your issue. Provide extensive detail and images if possible.
I was adding dialogues in the fnf mod then I went to test it, everything was fine until the third song loads, when the third song loads, it crashes, I checked mistakes in the source code but I didn't end up finding one
How do I fix this?

**Comment by OtasGamer64** [comment]
I am experiencing this as well.
