### ISSUE TITLE
How do i fix this lime windows error

### ISSUE THREAD

**Issue by Dramasso** [KadeDev/Funkin#2274]
i keep getting this message everytime: 
C:\Users\willi\OneDrive\Desktop\kade>lime test windows
source/DiffOverview.hx:65: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:411: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\willi\OneDrive\Desktop\kade\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by Dramasso** [comment]
also i did use the set default draw target command but it doesnt work

**Comment by vaasans** [comment]
i keeping geting  C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll bug how do i fix it

**Comment by Dramasso** [comment]
thats a different discussion

**Comment by Dramasso** [comment]
anyways kade engine is fixed for me this is now closed!
