### ISSUE TITLE
Error with adding assets

### ISSUE THREAD

**Issue by PumkinCheater** [KadeDev/Funkin#2279]
Hello,

![prrooof](https://user-images.githubusercontent.com/90822662/133651988-60fb3f3d-91a0-49d5-ad37-14ae5d79ea2e.PNG)
**what i have in the files,**

![outcome](https://user-images.githubusercontent.com/90822662/133652080-5a5a932d-1447-4583-bf1c-5f2f630169c1.PNG)
**what it looks like when i compile the game**

![prrrooof](https://user-images.githubusercontent.com/90822662/133652159-e0adc665-0b9d-44b6-bc95-5c1eb6a2bf5b.PNG)
**what i have in the files**

![outcome2](https://user-images.githubusercontent.com/90822662/133652199-d21e4b41-bc0b-485a-9d8e-8d5342e82ff8.PNG)
**the outcome**

I was just wondering if I could get some help with a little thing I'm struggling with. So whenever I add stuff onto the source code, like the main menu screen, app icons, etc, It doesn't show up. It only shows the default pictures that I replaced. This problem just kind of comes and goes, sometimes it happens, sometimes it won't. So I was just looking for some help on this problem that I keep having.

-Thank you!

**Comment by notmagniill** [comment]
please add a picture so that i could understand what your talking about.

Have a nice day!
Magniill.
