### ISSUE TITLE
Game wont load: Followed building.md several times- haven't touched any file

### ISSUE THREAD

**Issue by flypotato123** [KadeDev/Funkin#2282]
### #### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
**Tried, found three or four people with similar unresolved issues**

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
**Windows (`x86_64`)**

## What version of the game are you using? Look in the bottom left corner of the main menu.
**Couldn't check since it never even comes up, but I downloaded the latest (1.7) and also tried the one before (1.6.2)**

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
**just booting up the game, debug or normally**

## Please describe your issue. Provide extensive detail and images if possible.
**Whenever you launch lime test windows, there's a warning "FlxCamera.defaultCameras" but it doesn't do anything (from my research it's unrelated), it finishes the build perfectly, gets to the Kade engine logo screen and then the debug menu warns about the lack of [Test, offsettest and Tutorial]'s voice OGGs, which aren't supposed to be required, immediately afterwards it gets to 20/21 and crashes with a "null object reference" error.
![image](https://user-images.githubusercontent.com/58901050/133628484-36b88378-8bf8-4c1d-b1eb-60efd8ba2024.png)

Ive tried putting files to compensate for the missing OGGs (in the correct bins of course), yet it STILL warns for them**

Thanks in advance, Im literally out of options

SOLVED:
thanks to https://github.com/KadeDev/Kade-Engine/issues/2291

**Comment by isakube** [comment]
It tries to cache the vocals for songs that don't need them. it doesnt really matter

**Comment by Licht9** [comment]
> It tries to cache the vocals for songs that don't need them. it doesnt really matter

How do i fix it tho i get the same problem

**Comment by LiterallyLink** [comment]
I am also having this same issue. The game built fine the first time around, then attempted to load debug mode after adding a few new files. Started crashing, as such I removed the files to add them one by one but the game would crash by itself due to not being able to reference Voice.ogg files?

If anyone has solved this issue lmk. I will be testing my own fixes and update you if I figure anything out.

**Comment by Zunkz** [comment]
Hoping you get this fixed, I'm having the EXACT same issue.

**Comment by Zunkz** [comment]
Getting this same error, placed ogg files where it told me to and still getting it. 
![image](https://user-images.githubusercontent.com/52411518/133709407-a025f16e-4d5c-4258-b2e4-f65adef44947.png)

**Comment by flypotato123** [comment]
> It tries to cache the vocals for songs that don't need them. it doesnt really matter

that's the issue, it still crashes

**Comment by flypotato123** [comment]
Solved thanks to https://github.com/KadeDev/Kade-Engine/issues/2291
