### ISSUE TITLE
Bug Report: Game Crashes When Done Caching

### ISSUE THREAD

**Issue by Wyndelsore** [KadeDev/Funkin#2283]
Source code just crashes when done caching, this is happening to me in all versions, no file editing or code editing, simply crashes when done caching and changing to title state.

**Comment by NK-523** [comment]
It could be that gftitledance.png is missing its corresponding .xml.

**Comment by Zunkz** [comment]
> It could be that gftitledance.png is missing its corresponding .xml.

Why is this not in the source code??

**Comment by EliteMasterEric** [comment]
The cause of this particular bug is an update not to Kade, but to one of the dependencies (which explains why the bug occurs on old versions of the game as well).

I've found the root cause of the issue and a workaround fix people can use until an actual fix is put in place.

See #2291.

**Comment by Wyndelsore** [comment]
> The cause of this particular bug is an update not to Kade, but to one of the dependencies (which explains why the bug occurs on old versions of the game as well).
> 
> I've found the root cause of the issue and a workaround fix people can use until an actual fix is put in place.
> 
> See #2291.

It worked, TYSM!!!!
