### ISSUE TITLE
Kade Engine Crashing at the boot up screen

### ISSUE THREAD

**Issue by lespylol** [KadeDev/Funkin#2289]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
I saw more or less 5 same users having the same problem
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10 x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
Tested on KE 1.7 and KE 1.6.2, both had the same result, crashing
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No
## Please describe your issue. Provide extensive detail and images if possible.
So, when the loading number hits 21, the game just crashes, even when i don't mess with the source code
![image](https://user-images.githubusercontent.com/90264286/133710537-c54111d8-e037-4474-93e8-57f3d0b910a3.png)

Edit: I've tested with an another engine, it didn't crashed, but I'm used to code with KE

**Comment by Zunkz** [comment]
Pretty sure I'm having the same issue, still looking for a fix.

**Comment by Diamondiskewl** [comment]
I'm having the same exact issue, I've recompiled it from the source code twice and every time I test the same thing happens.

**Comment by planet12103** [comment]
Same somebody please fix this!

**Comment by LiterallyLink** [comment]
There's been multiple issues like this recently, I installed a very OLD previous version of KadeEngine that a friend and I had stored in google drive. I dont think it's the actual software, I think it may be an update from one or more of the Haxelib dependencies. I will investigate this further by using previous versions of the software.

**Comment by LiterallyLink** [comment]
So this might be a flixel version issue 

My friends version ![image](https://user-images.githubusercontent.com/67402756/133717761-cf52c68f-5cf2-4fa0-b459-87be164506d8.png)

My versions ![image](https://user-images.githubusercontent.com/67402756/133717747-6470dcd4-b414-429d-8c46-3ca8666d4c15.png)

I'll test this but if anyone else can test it as well it would be greatly appreciated.

**Comment by EliteMasterEric** [comment]
I've found the root cause of the issue and a workaround fix people can use until an actual fix is put in place.

See #2291.

**Comment by Zunkz** [comment]
> I've found the root cause of the issue and a workaround fix people can use until an actual fix is put in place.
> 
> See #2291.

What's the workaround?

**Comment by EliteMasterEric** [comment]
> > I've found the root cause of the issue and a workaround fix people can use until an actual fix is put in place.
> > 
> > See #2291.
> 
> What's the workaround?

In the meantime, developers looking for a quick fix can delete this line of code. Don't worry, it doesn't do anything useful... for now (see #2260).
https://github.com/KadeDev/Kade-Engine/blob/e0c5c578ad228284cc68fe10067aabafef9111dd/source/TitleState.hx#L57

**Comment by MrDDJ** [comment]
Yes, the same thing is being to me too. Is there a solution for now?

**Comment by lespylol** [comment]
> > > I've found the root cause of the issue and a workaround fix people can use until an actual fix is put in place.
> > > See #2291.
> > 
> > 
> > What's the workaround?
> 
> In the meantime, developers looking for a quick fix can delete this line of code. Don't worry, it doesn't do anything useful... for now (see #2260).
> https://github.com/KadeDev/Kade-Engine/blob/e0c5c578ad228284cc68fe10067aabafef9111dd/source/TitleState.hx#L57

my man 🤝

**Comment by akirawav3** [comment]
didnt work for me
