### ISSUE TITLE
[CRASH] Crash on title screen after caching / Null Object Reference related to Polymod

### ISSUE THREAD

**Issue by EliteMasterEric** [KadeDev/Funkin#2291]
If you are trying to build the game (Kade Engine, vanilla FNF, a lot of other engines, most mods built on Kade or Vanilla), there is currently a bug with the `polymod` dependency which causes the game to crash when attempting to load the title screen, after the caching step on KE and immediately on other engines.

This bug is caused by the fact that Polymod now checks for an `assetLibraryPaths` attribute in the `frameworkParams` the user passes to the init function. However, if `frameworkParams` itself is completely unspecified, attempting to access `frameworkParams.assetLibraryPaths` will throw a Null Object Reference and crash the program.

I have found the root cause and I'm working on a fix at larsiusprime/polymod#39.

In the meantime, developers looking for a quick fix can delete this line of code. Don't worry, it doesn't do anything useful... for now (see #2260).
https://github.com/KadeDev/Kade-Engine/blob/e0c5c578ad228284cc68fe10067aabafef9111dd/source/TitleState.hx#L57

**Comment by flypotato123** [comment]
You're a god, thanks!

**Comment by lespylol** [comment]
My man 🤝

**Comment by VodOSS** [comment]
why didnt i see this beforehand

**Comment by t9xi** [comment]
thank you so much!!!

**Comment by akirawav3** [comment]
Does not work.

**Comment by ghost** [comment]
could someone explain how to fix it?
because it took me a few days to get it to work but I couldn't do it

**Comment by ghost** [comment]
> could someone explain how to fix it?
> because it took me a few days to get it to work but I couldn't do it

I FINALLY FIX IT TYSM<3

**Comment by RealityFallen** [comment]
oh wait I used the old version and it worked. awesome.

**Comment by JackBlak** [comment]
master eric,
Despite reading everything, i kinda dont know where to start
The game sometimes crashes when trying to load the title screen, and im using 1.5.2
