### ISSUE TITLE
Bug Report: Compile Issue

### ISSUE THREAD

**Issue by SomeKindofGamer** [KadeDev/Funkin#2293]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
idk it just randomly happened
## Please describe your issue. Provide extensive detail and images if possible.
Everytime i try to compile kade engine it compiles but at the end it says "Failed to update resources" and nothing has changed in the game. How do i fix this?
code:
Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\tyler\Desktop\FNF\Development\Mod Pack\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/PlayState.cpp
 - src/ApplicationMain.cpp
 - src/lime/utils/AssetCache.cpp  [haxe,release]
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp

Failed to update resources

**Comment by RandomKidNow89** [comment]
the issue for me when I try to compile this is what happens:
PS C:\Users\-----\OneDrive\Documents\FNF Mods\Kade-Engine-stable> haxelib run lime test windows -debug
Error: Could not find haxelib "hxvm-luajit", does it need to be installed?
PS C:\Users\-----\OneDrive\Documents\FNF Mods\Kade-Engine-stable> haxelib install hxvm-luajit
Error: Failed with error: No such Project : hxvm-luajit
what should I do?
Note: the - is to remove my username but is not the problem

**Comment by SomeKindofGamer** [comment]
> the issue for me when I try to compile this is what happens:
> PS C:\Users-----\OneDrive\Documents\FNF Mods\Kade-Engine-stable> haxelib run lime test windows -debug
> Error: Could not find haxelib "hxvm-luajit", does it need to be installed?
> PS C:\Users-----\OneDrive\Documents\FNF Mods\Kade-Engine-stable> haxelib install hxvm-luajit
> Error: Failed with error: No such Project : hxvm-luajit
> what should I do?
> Note: the - is to remove my username but is not the problem

haxelib remove linc_luajit
haxelib remove hxvm-luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

**Comment by RandomKidNow89** [comment]
> > the issue for me when I try to compile this is what happens:
> > PS C:\Users-----\OneDrive\Documents\FNF Mods\Kade-Engine-stable> haxelib run lime test windows -debug
> > Error: Could not find haxelib "hxvm-luajit", does it need to be installed?
> > PS C:\Users-----\OneDrive\Documents\FNF Mods\Kade-Engine-stable> haxelib install hxvm-luajit
> > Error: Failed with error: No such Project : hxvm-luajit
> > what should I do?
> > Note: the - is to remove my username but is not the problem
> 
> haxelib remove linc_luajit
> haxelib remove hxvm-luajit
> haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
> haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

ok thank you

**Comment by SomeKindofGamer** [comment]
:)

**Comment by SomeKindofGamer** [comment]
im still having this issue
i tried restarting my pc and restarting git
it didn't work
i even re-installed haxe

**Comment by RandomKidNow89** [comment]
> im still having this issue
> i tried restarting my pc and restarting git
> it didn't work
> i even re-installed haxe

it wont work for me too

**Comment by RandomKidNow89** [comment]
hold on mines is doing something

**Comment by RandomKidNow89** [comment]
ok its fixed
