### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by vaasans** [KadeDev/Funkin#2297]
Source path "C:/Users/Daniel Ibeawuchi/OneDrive/Desktop/Kade-Engine-1.7/Kade-Engine-1.7/.haxelib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist 
how to fix this bug lime rebuild extension-webm windows  put this error                                                                             
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC    how do i fix these bugs

**Comment by A-Slippery-Slope** [comment]
You have to install the C++ pack for Visual Studio 2019
