### ISSUE TITLE
Bug Report: Cant Rebuild A Windows64 extension-webm Linux

### ISSUE THREAD

**Issue by Wyndelsore** [KadeDev/Funkin#2298]
So, I've been trying to do this for a big time and can't get it working, when I try to do a lime test linux the game just crashes, and when I try running lime test windows it just shows this: Source path "/home/supermiiu/haxelib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist
So what I've tried is cloning the Windows .ndll and naming the folder Windows64, or copying a windows a windows 64 .ndll, both show the same error:
WebmPlayer.hx:3: characters 8-15 : You cannot access the cpp package while targeting neko (for cpp.Lib)
source/Main.hx:4: characters 8-23 : ... referenced here
export/release/neko/haxe/ApplicationMain.hx:299: characters 48-52 : ... referenced here

I hope someone can help me fix this.

**Comment by swordcube** [comment]
have you done **lime rebuild extension-webm linux**?

**Comment by Wyndelsore** [comment]
> have you done **lime rebuild extension-webm linux**?

yes but the game crashes with lime test linux
