### ISSUE TITLE
base crashes at 20/21

### ISSUE THREAD

**Issue by VodOSS** [KadeDev/Funkin#2302]
so when im launching kade engine after ive built it using `lime build windows`, it just crashes at 20/21

why does this happen,

and how can i fix this?,

im using KE 1.7 btw

**Comment by MrDDJ** [comment]
I have this problem too

**Comment by t9xi** [comment]
i also have this problem

**Comment by kal-bit** [comment]
I have the same problem does anyone know how to fix it

**Comment by Dobby233Liu** [comment]
take a look at this: https://github.com/KadeDev/Kade-Engine/issues/2291
