### ISSUE TITLE
Enhancement: Uhm..

### ISSUE THREAD

**Issue by ghost** [KadeDev/Funkin#2303]
## What is your suggestion, and why should it be implemented?
I am on a Mac and i want to move the strumline on songs but on Mac lua modcharts doesnt work soooo soemone can make that strumline movement can also be moved because if i hardcode a FlxTween it says strumline has not field Y sooo

**Comment by ghost** [comment]
Also i do not know if this is the right place but how i can apply to become a contributor of this repo (no forks, original, write access bla).

**Comment by NotSorena** [comment]
development is cancelled
