### ISSUE TITLE
what

### ISSUE THREAD

**Issue by HiroMizuki** [KadeDev/Funkin#2313]
![image](https://user-images.githubusercontent.com/72695242/133911908-b3f4bef8-6494-4f0c-9e25-f141489f4841.png)

i was testing my mod
when i tried to enter tutorial in freeplay, i got that error
help pls

**Comment by Dobby233Liu** [comment]
check your freeplaySonglist.txt file, it may be corrupt

**Comment by HiroMizuki** [comment]
> check your freeplaySonglist.txt file, it may be corrupt

ok i'll check it

**Comment by HiroMizuki** [comment]
> check your freeplaySonglist.txt file, it may be corrupt

well, i've checked here and still didn't worked

**Comment by HiroMizuki** [comment]
i'll try to unzip an other kade engine folder
