### ISSUE TITLE
Bug Report: Null Object Reference at start

### ISSUE THREAD

**Issue by spidedev** [KadeDev/Funkin#2315]
I build the 1.7 Kade Engine and all nice and dandy until the actual game loads to 21 and 'Null Object Reference' Appears, please help i've been dealing with this the last two days.

**Comment by BinaricMC** [comment]
open powershell and type in **lime test windows -debug**

Hope this helps

**Comment by Alt-Reality** [comment]
follow the steps on this page follow the steps on this github page larsiusprime/polymod#39
till this is merged into source code, new users building their game will be met with a crash because of a new polymod thing.

**Comment by spidedev** [comment]
massive lifesaver, thanks!

> follow the steps on this page follow the steps on this github page [larsiusprime/polymod#39](https://github.com/larsiusprime/polymod/pull/39)
> till this is merged into source code, new users building their game will be met with a crash because of a new polymod thing.
