### ISSUE TITLE
Bug Report: Game crashes when importing custom character

### ISSUE THREAD

**Issue by OtasGamer64** [KadeDev/Funkin#2318]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10, 64-bit

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No, not yet.

## Please describe your issue. Provide extensive detail and images if possible.
When I change the second player to my custom character in any song, it just crashes instantly. I'm pretty sure everything is set up correctly (code, .xmls, icons, etc.).

**Comment by OtasGamer64** [comment]
UPDATE: This happens with any asset change with any character.

**Comment by Kade-github** [comment]
super old issue, closing because its so old. idk why this isn't stale?? dumbass actions
