### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dartthe6th** [KadeDev/Funkin#2320]
When it finishes loading it just crashes
It's after the caching loads
looks like the video file wont upload

**Comment by Junicko** [comment]
I've got this issue too

**Comment by Alt-Reality** [comment]
follow the steps on this github page https://github.com/larsiusprime/polymod/pull/39

**Comment by dartthe6th** [comment]
> follow the steps on this github page [larsiusprime/polymod#39](https://github.com/larsiusprime/polymod/pull/39)

thanks lots!

**Comment by dartthe6th** [comment]
lemme close this rq-
