### ISSUE TITLE
Kade Engine Loading Stuck at 20/21 then proceeds to crash

### ISSUE THREAD

**Issue by SoftieIsVibing** [KadeDev/Funkin#2322]
So, i wanted to begin making fnf mods 
so i started by using a tutorial (https://youtu.be/CKNfu8G9EOc) and i did everything i needed to do
but then, when i opened windows powershell and typed "lime test windows" kade engine opened and it loaded up to 20/21
then it just, crashed with the error code shown below , i redownloaded it and still nothing
please, can i have some help? thanks.
![](https://media.discordapp.net/attachments/823697325541031937/889247919193075772/image0.png)

**Comment by Alt-Reality** [comment]
friend had this same problem, followed the steps on this page and it fixed it for him https://github.com/larsiusprime/polymod/pull/39

**Comment by SoftieIsVibing** [comment]
> friend had this same problem, followed the steps on this page and it fixed it for him [larsiusprime/polymod#39](https://github.com/larsiusprime/polymod/pull/39)

Okay thank you so much it works now !! :)
