### ISSUE TITLE
Error: Could not find haxelib "extension-webm", does it need to be installed?  ( - Windows10

### ISSUE THREAD

**Issue by FnafPizzaFan** [KadeDev/Funkin#2323]
I've been stuck on this issue for so long and I need help I've installed everything I needed but whenever I do 
haxelib git extension-webm https://github.com/KadeDev/extension-webm
haxelib run lime rebuild extension-webm windows
it gives me this message
![Screenshot 2021-09-19 204356](https://user-images.githubusercontent.com/90162306/133948396-f25acbd1-2c23-44ed-9469-65bba8e43d98.png)

The latest version of the kade engine

**Comment by ghost** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/82221237/133963165-c5fa95f5-bc3b-40ba-bcb0-baabba288ee7.png)

**Comment by ghost** [comment]
I tried to fix, but now, I have that :
![image](https://user-images.githubusercontent.com/82221237/133982976-583e9313-64b8-412e-b01f-3936d553e841.png)
"Impossible d'ouvrir le fichier source" is french, it mean "Unable to open source file".

**Comment by ghost** [comment]
> I tried to fix, but now, I have that :
> ![image](https://user-images.githubusercontent.com/82221237/133982976-583e9313-64b8-412e-b01f-3936d553e841.png)
> "Impossible d'ouvrir le fichier source" is french, it mean "Unable to open source file".

I tried to uninstall and install again, it didn't fix it.

**Comment by ghost** [comment]
here
haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
lime rebuild exetension-webm windows/linux/mac
*dont put the windows/linux/mac put your os name there*

**Comment by ghost** [comment]
> here
> haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
> lime rebuild exetension-webm windows/linux/mac
> _dont put the windows/linux/mac put your os name there_
same thing
![image](https://user-images.githubusercontent.com/82221237/134400385-a7580d24-aebe-4632-9d91-a0818e4ef09e.png)

**Comment by ghost** [comment]
Why does it add an e to extension ?

**Comment by ghost** [comment]
without "e", same problem than before :
![image](https://user-images.githubusercontent.com/82221237/134401706-dafbe061-5b27-42bd-8ecf-03d0df48db9b.png)

**Comment by ALX-00** [comment]
What architecture you have? Is it x64 or x86? maybe you can try to put and -64 or -32 at the end depending of the architecture you use. I say this as have compiled the game for windows 32 bit and it chrashes on a 64 bit computer but works on a 32 bit one.

**Comment by ghost** [comment]
> What architecture you have? Is it x64 or x86? maybe you can try to put and -64 or -32 at the end depending of the architecture you use. I say this as have compiled the game for windows 32 bit and it chrashes on a 64 bit computer but works on a 32 bit one.

Yeah, IT'S WORKING ! Thanks !
