### ISSUE TITLE
Kade Crashes at Title

### ISSUE THREAD

**Issue by akirawav3** [KadeDev/Funkin#2324]
Kade Engine 1.4.2, x64 crashes before title screen
No music plays, it says 126 fps each time, and just closes with no crash log or errors that make any sense.
It just says this :
C:\Users\Alyza\Desktop\Deltarune Funkin'>lime test windows
source/PlayState.hx:478: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/0,0,2//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\Alyza\Desktop\Deltarune Funkin'\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/lime/utils/AssetCache.cpp  [haxe,release]
 - src/ApplicationMain.cpp
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
source/TitleState.hx:63: Loaded 1 assets (DEFAULT)
source/Discord.hx:13: Discord Client starting...
source/Discord.hx:63: Discord Client initialized
source/Discord.hx:20: Discord Client started.

I've tried debug, not debug, other consoles. Nothing works. I've tried the new polymod update to fix it, removing that line of code from titlestate, nothing works. It was working fine less than an hour ago, and i restarted it to change a song and now refuses to work.

**Comment by Alt-Reality** [comment]
follow the steps on this github page larsiusprime/polymod#39
till this is merged into source code, new users building their game will be met with a crash because of a new polymod thing.

**Comment by akirawav3** [comment]
I just said that didn't work.. :/

**Comment by Alt-Reality** [comment]
its probably because of the things u deleted. try doing it on a clean set of kade engine

**Comment by NotSorena** [comment]
First of all... WHY ARE YOU USING KADE ENGINE 1.4.2

**Comment by akirawav3** [comment]
> First of all... WHY ARE YOU USING KADE ENGINE 1.4.2

Because newer versions suck? Lol?

**Comment by akirawav3** [comment]
> its probably because of the things u deleted. try doing it on a clean set of kade engine

It is a new set.

**Comment by NotSorena** [comment]
@akirawav3 Hm yes. The only thing the newer versions suck at is being stable

**Comment by AbnormalPoof** [comment]
true tbh
