### ISSUE TITLE
Question: Character switch event

### ISSUE THREAD

**Issue by TNT-King** [KadeDev/Funkin#2325]
Do u need to be on a special version of Kade Engine to make character switch event or can i just use any version?

**Comment by kosmakyo** [comment]
i know that in at least 1.5.4 you can do this in playstate.hx

under 
```
override function beatHit()
	{
```
put
```
if (curSong == '-song name-') 
			{
				switch (curBeat)
				{
					case -beat you want the event to happen at-:
						remove(dad);
						dad = new Character(100, 100, '-new character name-');
						add(dad);
				 }
			}
```
you should also refer to this https://gamebanana.com/tuts/13798

**Comment by TNT-King** [comment]
Thanks it worked :D
