### ISSUE TITLE
Project.xml... ._.

### ISSUE THREAD

**Issue by CBa08** [KadeDev/Funkin#2328]
It's the same thing everyone has been saying and I still don't understand how to fix it.

**Comment by NK-523** [comment]
Does it say 
![image](https://user-images.githubusercontent.com/77185327/134069785-89e661cf-7453-4a1e-9a3a-ac69228e58af.png)
Because if so, just deselect the folder you have selected or select the kade engine folder

**Comment by NK-523** [comment]
then click "file" then "open windows powershell"

![image](https://user-images.githubusercontent.com/77185327/134070315-27f257bc-9e40-40d0-abf8-bf41ff3a3973.png)

(Or your OS' equivalent)

**Comment by CBa08** [comment]
tysm!

**Comment by Hythrex** [comment]
> tysm!

then please close this
