### ISSUE TITLE
Bug Report: The game crashes when caching the stuff

### ISSUE THREAD

**Issue by Flowcheer** [KadeDev/Funkin#2329]
This bug happens in KE 1.7.
When finishing caching, the game stops responding and gets stuck on 20/21.

This is what happens
![image](https://user-images.githubusercontent.com/79985497/134085955-5e8697d3-7e2a-4573-aa1c-c65cad7cbf22.png)
 
Pls help

**Comment by RommelHamieh** [comment]
it also happened to me 
in my case the Windows SDK (10.0.17763.0) was not installed i think you need to install it Via MVS

https://gyazo.com/8eeac2ab13cef441ff8017bd630550b3
click on Modify 
https://gyazo.com/f912b2c4725c365a083b8d3f9489cf21
 Windows SDK (10.0.17763.0) will appear on the right side of the image , Install it and try compiling the game 
if it kept crashing follow the instructions on this link
https://github.com/KadeDev/Kade-Engine/issues/2327#issuecomment-923182237

**Comment by Flowcheer** [comment]
It worked! tysm!
