### ISSUE TITLE
Kade Engine Keeps Crashing

### ISSUE THREAD

**Issue by theoneyoushouldnotknow** [KadeDev/Funkin#2330]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 64 bit.

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Start the game and wait until caching finishes.

## Please describe your issue. Provide extensive detail and images if possible.
I have the Null Object Reference error still, even after following all the steps provided by MasterEric, removed that line of code from TitleState.hx, installed the modified polymod version, and... I still get the error.

**Comment by lyupro** [comment]
Also have such kind of error from 1.4.2 till 1.6.2 versions (each of it give Null Object Reference error).
How to fix it? Would be grateful for any help
![unknown](https://user-images.githubusercontent.com/45335183/134827640-6e2a83ef-6fed-4113-bdd5-4e918c5d3352.png)
!
