### ISSUE TITLE
Bug Report: Kade Engine won't compile on Manjaro Linux

### ISSUE THREAD

**Issue by aliwahabdev** [KadeDev/Funkin#2333]
I'm currently trying to compile Kade Engine on Manjaro Linux and it keeps giving me errors.
I have installed everything that was on the GitHub.io page. Are there any solutions for this?
`
Error: In file included from ./src/LuaCharacter.cpp:6:
/home/ali/haxelib/linc_luajit/git//linc/linc_lua.h:10:10: fatal error: ../lib/lua/src/lua.hpp: No such file or directory
   10 | #include "../lib/lua/src/lua.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by ghost** [comment]
have you installed everything? that you need to compile

**Comment by Dobby233Liu** [comment]
Library bug https://github.com/KadeDev/Kade-Engine/issues/2074

**Comment by aliwahabdev** [comment]
Thanks man! I just got it working now.
