### ISSUE TITLE
Shows no difficulties for the chart even though there is difficulties for the chart.

### ISSUE THREAD

**Issue by NotSorena** [KadeDev/Funkin#2345]
![image](https://user-images.githubusercontent.com/89949310/134443267-c76ad013-df1e-4dd0-8315-8b3a1d9b3655.png)

**Comment by NotSorena** [comment]
Note: After pressing "OK" the game crashes.

**Comment by Jotaro-Gaming** [comment]
its probably because of the spaces in the chart you should put a "-" instead of the space

**Comment by NotSorena** [comment]
@MrClogsworthYT Im using KE 1.7, and it supports spaces. I'll try that though.
