### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Normalhuman1475** [KadeDev/Funkin#2348]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
It doesn't work.
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Im using linux.
## What version of the game are you using? Look in the bottom left corner of the main menu.
The latest version 
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No.
## Please describe your issue. Provide extensive detail and images if possible.
Im trying to build kade engine on Visual Studio Code, but everytime i run "lime build linux", It keeps sending me to this message and importing the export file without the game.
![Screenshot 2021-09-23 10 33 44 AM](https://user-images.githubusercontent.com/89854107/134529735-266d006a-5e8f-42bc-bee4-117f7ce67569.png)
So then I do it manually and insert "--dce std" and then this message pops up.
![Screenshot 2021-09-23 10 34 59 AM](https://user-images.githubusercontent.com/89854107/134529848-f5d15450-de1b-4157-815b-053843c091a5.png)
But it is where the project.xml file is in. 
Please help asap, I have been struggling for days now.

**Comment by Oksydoksy** [comment]
Try to change the "p" at the project.xml to lowercase if its lowercase change it to capital it works for me(for example Project.xml to project.xml or project.xml to Project.xml). If it doesnt work try uninstalling haxe and installing it back might work too.

**Comment by Normalhuman1475** [comment]
> Try to change the "p" at the project.xml to lowercase if its lowercase change it to capital it works for me(for example Project.xml to project.xml or project.xml to Project.xml). If it doesnt work try uninstalling haxe and installing it back might work too.

Ok, im trying it now

**Comment by Normalhuman1475** [comment]
> > Try to change the "p" at the project.xml to lowercase if its lowercase change it to capital it works for me(for example Project.xml to project.xml or project.xml to Project.xml). If it doesnt work try uninstalling haxe and installing it back might work too.
> 
> Ok, im trying it now
i just reinstalled haxe and everything else and it still doesnt work 😰
