### ISSUE TITLE
question without importance and just curiosity

### ISSUE THREAD

**Issue by HiroMizuki** [KadeDev/Funkin#2352]
**what the fuck is that sound at art folder lol**

![image](https://user-images.githubusercontent.com/72695242/134605641-a296d1d8-f955-4f40-88df-dc551b9ec270.png)

**Comment by isakube** [comment]
from vanilla. its some tv scan thing. lore????

**Comment by HiroMizuki** [comment]
> This issue was closed because it has become stale

i think i hate u
