### ISSUE TITLE
It seems like I have installed the ARM64 version of VSC2019 and I need to download the x64 version. Any idea on how to fix this? 

### ISSUE THREAD

**Issue by StickDeveloper** [KadeDev/Funkin#2356]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Jotaro-Gaming** [comment]
lmao lime cant build arm unless its for android or ios lmaoooooooooo

**Comment by StickDeveloper** [comment]
Then how do I fix this?
