### ISSUE TITLE
i followed a tutorial about adding characters, i followed it but now when i type "lime test windows"  it says this "source/Character.hx:400: characters 5-9 : Expected }"

### ISSUE THREAD

**Issue by berrrrk** [KadeDev/Funkin#2358]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Hythrex** [comment]
1. This is *your* skill issue
2. Please show where line 400 is and the lines near it
3. Please describe what tutorial you followed from
