### ISSUE TITLE
Error: LuaCharacter.cpp

### ISSUE THREAD

**Issue by Ashiruzaki** [KadeDev/Funkin#2366]
When I type lime test windows, it says:
Error: LuaCharacter.cpp
./src/LuaCharacter.cpp(121): error C2039: 'error': is not a member of 'linc::lual'
C:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(129): error C3861: 'error': identifier not found

How can I fix this? I'm pretty new to modding.

**Comment by nekobot64** [comment]
I'm having the same issue on macOS + Linux (pop!OS) and i'm yet to find a solution

**Comment by somefnfplayerlol** [comment]
@MasterEric your lua rework seems to be malfunctioning

**Comment by JOELwindows7** [comment]
linking #2375

**Comment by DrewBuan** [comment]
step 1: Run haxelib remove linc_luajit
step 2 : Run haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit 0af04cd3a1 

no more error

**Comment by EliteMasterEric** [comment]
@Drewplayz solution is bad because it reverts the change that fixes builds on Linux.

The correct solution is:

```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit c5d2831
```

Note a different commit hash was chosen.

**Comment by Ashiruzaki** [comment]
@MasterEric WOW thx! Also after that there's a polymod problem and while I'm trying to find the solution to fix it, I saw yours and it works perfectly! You are the best! For the rest, you all did your best to help.
