### ISSUE TITLE
LuaCharacter error

### ISSUE THREAD

**Issue by Charmandorp357** [KadeDev/Funkin#2370]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.
i get an error like this when i try to build the game i did all the steps to fix most of the errors but not this one
./src/LuaCharacter.cpp(121): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(129): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(142): error C2039: 'pushcfunction': is not a member of 'linc::lua'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(21): note: see declaration of 'linc::lua'
./src/LuaCharacter.cpp(145): error C3861: 'pushcfunction': identifier not found
./src/LuaCharacter.cpp(150): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(153): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(166): error C2039: 'pushcfunction': is not a member of 'linc::lua'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(21): note: see declaration of 'linc::lua'
./src/LuaCharacter.cpp(169): error C3861: 'pushcfunction': identifier not found
./src/LuaCharacter.cpp(174): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(177): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(182): error C2039: 'pushcfunction': is not a member of 'linc::lua'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(21): note: see declaration of 'linc::lua'
./src/LuaCharacter.cpp(185): error C3861: 'pushcfunction': identifier not found
./src/LuaCharacter.cpp(190): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(193): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(198): error C2039: 'pushcfunction': is not a member of 'linc::lua'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(21): note: see declaration of 'linc::lua'
./src/LuaCharacter.cpp(201): error C3861: 'pushcfunction': identifier not found
./src/LuaCharacter.cpp(206): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(209): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(214): error C2039: 'pushcfunction': is not a member of 'linc::lua'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(21): note: see declaration of 'linc::lua'
./src/LuaCharacter.cpp(217): error C3861: 'pushcfunction': identifier not found
./src/LuaCharacter.cpp(222): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(225): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(308): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(308): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(351): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(351): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(380): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(380): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(408): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(408): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(439): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(439): error C3861: 'error': identifier not found
./src/LuaCharacter.cpp(468): error C2039: 'error': is not a member of 'linc::lual'
E:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual'
./src/LuaCharacter.cpp(468): error C3861: 'error': identifier not found

how do i fix it?

**Comment by BL0KYBL0K** [comment]
same
