### ISSUE TITLE
My game isn't built

### ISSUE THREAD

**Issue by ghost** [KadeDev/Funkin#2376]
When I use "lime build windows -debug", the game isn't built, there is assets, but no "Kade Engine.exe".
Can someone explain me why nothing append ?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/82221237/134824574-a4d6928e-9839-40cb-b328-c278a9684454.png)

**Comment by lyupro** [comment]
The same situation.. hope devs let us know what do we need to make a build.

**Comment by BL0KYBL0K** [comment]
same here

**Comment by somefnfplayerlol** [comment]
looks like there is a problem with lua

**Comment by ghost** [comment]
Realy?! I did'nt see that in my screenshoot ! (lol)

**Comment by ghost** [comment]
Where can I find it?

**Comment by somefnfplayerlol** [comment]
no, its a problem with `linc_luajit`

**Comment by somefnfplayerlol** [comment]
ill notify @MasterEric about this

**Comment by JOELwindows7** [comment]
Linking issue #2375 . [something](https://github.com/nebulazorua/linc_luajit ) has screwed up
