### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by NotIlulus** [KadeDev/Funkin#2377]
So, you know like in the week 7 thing when you get a "Sick!" The note effect sparkles? Just wondering how to do that. Help!

**Comment by i-winxd** [comment]
can't be done until week 7 source releases...
...aka likely in 1000 years

**Comment by glisteningtwilights** [comment]
It can be done as I have seen it used before in engines so it is possible I just don't know how to do it, Sorry.
