### ISSUE TITLE
Bug Report: Building in 1.7 Results in Charts Getting Messed up

### ISSUE THREAD

**Issue by SuxxorState** [KadeDev/Funkin#2379]
[1.7 Windows 64-bit]

In this version of the Kade Engine, after compiling the game, a few charts sporadically and randomly get messed up. any sustains on notes are deleted and any animations in the background that loop (idles) never run, and camera movements dont happen. I've tested this and it seems to be the charts themselves that are the issue. putting in a chart that came from somewhere else seems to resolve the issue on that particular chart. I don't know what causes this to happen, but it might need to be looked into sooner or later.

**Comment by ScarabWasTaken** [comment]
Needs more details, record a before and after

**Comment by SuxxorState** [comment]
> Needs more details, record a before and after

got it, ill do so in a few hours. otherwise, i dont know what else to elaborate.
