### ISSUE TITLE
Bug Report: Compilation error

### ISSUE THREAD

**Issue by DrawerAnim** [KadeDev/Funkin#2381]
C:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h(34): note: see declaration of 'linc::lual' ./src/LuaCharacter.cpp(468): error C3861: 'error': identifier not found #2375

How to fix it?

**Comment by SuxxorState** [comment]
haxelib remove linc_luajit
haxelib remove hxvm-luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

have ya tried this?

**Comment by DrawerAnim** [comment]
> haxelib remove linc_luajit
> haxelib remove hxvm-luajit
> haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
> haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
> 
> have ya tried this?

Yes, I tried this😶
