### ISSUE TITLE
Bug Report: Lua Character Error

### ISSUE THREAD

**Issue by BL0KYBL0K** [KadeDev/Funkin#2392]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
i have reinstalled a few times and it still wont work
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
i use windows 10
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7 (latest release)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
i never changed a single line of code and yet i get this 
![image](https://user-images.githubusercontent.com/88749184/135106301-e5381320-6233-410c-bbad-0ad19b1ac8d6.png)

## Please describe your issue. Provide extensive detail and images if possible.
I had just finished following brightfires tutorial on build 1.7 because i could build the other versions just fine and yes i did update all the needed exentions or whatever you call them and i even reinstalled  hxvm-luajit with the latest release and i did the same with linc_luajit but i still get this error 
![image](https://user-images.githubusercontent.com/88749184/135106697-8cde654a-8aa0-4a17-8da6-2b139a58a838.png)

i dont know what to do i have reinstalled everything twice now i have re downloaded the kade engine source code a few times and yet no matter what it wont work please help me

**Comment by MaiBatchis** [comment]
Helllo!

Sorry, I wish I could help but I don't know how to code yet, and I'm having the same problem. TT

**Comment by DrewBuan** [comment]
I'm getting the same bug too, It's also bad because I'm using kade engine for a school project

**Comment by MaiBatchis** [comment]
Yeah... Wait- For a school project?! O shit- I hope someone helps us soon! ^^

**Comment by OtasGamer64** [comment]
The reason why this error is happening is because a problematic commit was committed on [https://github.com/nebulazorua/linc_luajit](https://github.com/nebulazorua/linc_luajit).
I really hope this will get fixed.

**Comment by MaiBatchis** [comment]
> The reason why this error is happening is because a problematic commit was committed on https://github.com/nebulazorua/linc_luajit. I really hope this will get fixed.

Oh oki! Yeah, I hope it gets fixed. TT

**Comment by RealReal334** [comment]
I hope They see this and Fix it soon Seems like i can't fix it by myself

**Comment by MaiBatchis** [comment]
Yeah... We can't fix it ourselves 'cause it's a plugin/extension (I think), so only the creator can fix it. "TT

**Comment by OtasGamer64** [comment]
I found a fix!
"haxelib remove linc_luajit"
"haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit 0af04cd3a1"

And it should work!
