### ISSUE TITLE
Bug Report: Project.xml

### ISSUE THREAD

**Issue by Normalhuman1475** [KadeDev/Funkin#2393]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Linux but any help would work
## What version of the game are you using? Look in the bottom left corner of the main menu.
I think 1.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no
## Please describe your issue. Provide extensive detail and images if possible.
Everytime i try to lime build it just keeps saying
![Screenshot 2021-09-28 4 01 39 PM](https://user-images.githubusercontent.com/89854107/135157538-6d8bf64a-a56f-4e96-bbc6-24aba5e97cdd.png)
Please help the project.xml is in the same place, i never moved it.

**Comment by Hythrex** [comment]
bruj\

**Comment by Hythrex** [comment]
please close this 
this is not a bug

**Comment by Normalhuman1475** [comment]
ok, sorry.
