### ISSUE TITLE
Why the heck is this happening

### ISSUE THREAD

**Issue by ItsIsaacIO** [KadeDev/Funkin#2394]
![image](https://user-images.githubusercontent.com/75589176/135176016-ca7ac334-39b0-4ff6-9958-d1f9d8d3064a.png)

**Comment by DrewBuan** [comment]
That is happening to me too

**Comment by hyperchaostudios** [comment]
Do haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit 0af04cd3a1 (It will work)
Just you need to put the branch (0af04cd3a1)
