### ISSUE TITLE
Enhancement: Custom Difficulties

### ISSUE THREAD

**Issue by EliteMasterEric** [KadeDev/Funkin#2398]
We should allow mods to include songs with Noob/Expert/Insane difficulties, for example, without modifying the engine code.

**Comment by Reycko** [comment]
Use Mic'd Up Engine.

**Comment by isakube** [comment]
> Use Mic'd Up Engine.

bad

My idea is that when we check the charts in freeplay menu to see if the difficulties exist, we check for other charts besides Easy, Normal, and Hard. we take those charts' difficulty suffixes and add them to the available difficulties for that chart. Freeplay-only implementation, but it's a start. Obv more complicated than this explanation though

**Comment by Reycko** [comment]
You know that when i asked for it a long time ago, Kade himself said no.
So sorry but its Mic'd Up Engine or you do the update urself

**Comment by isakube** [comment]
ayo @MasterEric close the issue if you posted it here????

**Comment by EliteMasterEric** [comment]
I'll close this if Kade declined it already

**Comment by Sylveondev** [comment]
> You know that when i asked for it a long time ago, Kade himself said no. So sorry but its Mic'd Up Engine or you do the update urself

Doesn't Agoti use Mic'd up?

**Comment by EliteMasterEric** [comment]
> 
> 
> > You know that when i asked for it a long time ago, Kade himself said no. So sorry but its Mic'd Up Engine or you do the update urself
> 
> Doesn't Agoti use Mic'd up?

For reference, [Enigma Engine](https://enigmaengine.github.io) (currently in development) supports custom difficulties.
