### ISSUE TITLE
haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm is taking too much time for updating

### ISSUE THREAD

**Issue by undertaule** [KadeDev/Funkin#2399]
I've been trying to download the extension for a while and it's stuck on this message for 10 hours

I really need help 

![probleme](https://user-images.githubusercontent.com/91559421/135259127-026433c5-82fa-4041-8361-6b33b97c4b8e.PNG)

**Comment by ishsharm0** [comment]
you should be using [kadedev's fork of extension webm](https://github.com/KadeDev/extension-webm), not gwebdev's
