### ISSUE TITLE
Enhancement: Better speed system

### ISSUE THREAD

**Issue by Reycko** [KadeDev/Funkin#2400]
## What is your suggestion, and why should it be implemented?
So the speed system is a bit buggy (especially the hitboxes going crazy) and i think we should have a rewrite / Better version of the system.

(Note: Also the notes are buggy)

**Comment by SomeKindofGamer** [comment]
The Speed System is VERY bugged.
The song ends too early if you slow the song
AND THE HITBOXES GOD
and the zoom and gf literally has a seizure

**Comment by Reycko** [comment]
> The Speed System is VERY bugged. The song ends too early if you slow the song AND THE HITBOXES GOD and the zoom and gf literally has a seizure

ikr
