### ISSUE TITLE
Bug Report: kade 1.5.2 crashes when i compile it

### ISSUE THREAD

**Issue by asdsdaasdxasd** [KadeDev/Funkin#2407]
Hello, I am trying to fix something for the mod so my friend sent me the folder. but when i try to compile it this happens.

![image](https://user-images.githubusercontent.com/83480814/135534911-7a0349e5-cda3-4b75-89ee-f8e12797ae85.png)

Trying to fix this but i cant.
Thanks.

**Comment by RagdollClash** [comment]
wouldn't that mean that it compiled, if it created the executable?

**Comment by UnsealedWraith** [comment]
yeah i have this exact same issue, not entirely sure how to fix it but someone told me it could be because of polymod
