### ISSUE TITLE
Bug Report: Crashing after load screen is done

### ISSUE THREAD

**Issue by DrewBuan** [KadeDev/Funkin#2408]
When the game fully loads up, the game crashes right after it hit 21/21, please help me fix this

**Comment by RealReal334** [comment]
Me too Kade Engine 1.7 is Very Buggy

**Comment by NikRetaNCAM** [comment]
Try going into TitleState.hx and removing the first polymod line you''ll see.

**Comment by TheRealJake12** [comment]
> Try going into TitleState.hx and removing the first polymod line you''ll see.

or just doing
haxelib remove polymod

haxelib git polymod https://github.com/MasterEric/polymod

it redoes the polymod thing before kade did something

**Comment by astronomical-sandpaper** [comment]
whenever i reinstall polymod it says "Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command"

**Comment by astronomical-sandpaper** [comment]
> whenever i reinstall polymod it says "Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command"

nvm i found the issue
