### ISSUE TITLE
Bug Report: Game Crash

### ISSUE THREAD

**Issue by Biraru** [KadeDev/Funkin#2417]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows(64)

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE-1.6

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

I Open The Game And It Crashes

## Please describe your issue. Provide extensive detail and images if possible.

I Just Open The Game After Compling It And It Crashes

**Comment by TheRealJake12** [comment]
try uninstalling the polymod used for this and use mastererics fork of it
use this and it should work
haxelib remove polymod
haxelib git polymod https://github.com/MasterEric/polymod

**Comment by Lubario** [comment]
@TheRealJake12 Thank you soo much, i had the same problem as this dude, and you fixed it.

**Comment by ImJun000** [comment]
@TheRealJake12 OMG I DONT KNOW HOW TO THANK YOU YOU ARE MY SAVIOR SINCE MY SONG AND MY CHARACTER IS READY AND THE GAME JUST CANT LAUNCH

**Comment by astronomical-sandpaper** [comment]
@TheRealJake12 i reinstalled polymod but i still get the same error, i use ke 1.4.2

**Comment by ghost** [comment]
@TheRealJake12 It didn't work
