### ISSUE TITLE
Bug Report: Idle animations and camera break in story mode

### ISSUE THREAD

**Issue by Sesor33** [KadeDev/Funkin#2422]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE 1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Go to story mode, play a week. Breaks 100% of the time.

## Please describe your issue. Provide extensive detail and images if possible.

Upon entering the second and third song in the week, idle animations no longer play, and the camera stays locked onto Boyfriend. This only happens when attempting to play the second and third songs through the full week. Playing the songs through freeplay works fine.

Video example: https://youtu.be/X7IrP4k8hLU

**Comment by ishsharm0** [comment]
Can confirm, also gets rid of sustain notes on 2nd song and above.
