### ISSUE TITLE
Bug Report: VS Impostor Version 3.01 Kade Engine 1.6 Crashes

### ISSUE THREAD

**Issue by Icey67** [KadeDev/Funkin#2424]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 11(Insider Preview Beta) x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
Game Version 3.01, Kade Engine 1.6
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Options>Gameplay and then Customize Gameplay
## Please describe your issue. Provide extensive detail and images if possible.
I'm just trying to get the "Sicks" away from my Notes when I'm playing anything (especially "Defeat") but can't because then the Game just Crashes

**Comment by SanicBTW** [comment]
You should report this to the vs impostor team, not to the engine
