### ISSUE TITLE
Bug Report: when i try to rebuild extension webm it says that the command syntax is incorrect

### ISSUE THREAD

**Issue by WillTheGrunt** [KadeDev/Funkin#2426]
when i try typing lime rebuild extension-webm <ie. windows, macos, linux> in the cmd of my computer it keeps saying that the command syntax is incorrect, can someone help me

**Comment by DrewBuan** [comment]
you need to install Visual Studio 2019 or XCode First.

**Comment by WillTheGrunt** [comment]
i downloaded it

**Comment by WillTheGrunt** [comment]
i did it
