### ISSUE TITLE
This Will Fix Most of The Recent Kade Engine Errors Out There

### ISSUE THREAD

**Issue by DrewBuan** [KadeDev/Funkin#2429]
1. If your extension-webm isn't rebuilding.

How to Fix:
You need to install VS 2019 or XCode first

2. If you get LuaCharacter Error.

How to fix:
In your command line Application, put in these commands in order
- haxelib remove linc_luajit
- haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit 0af04cd3a1

3. If your game crashes after loading screen.

How to fix:
go to title.hx then delete the first polymod, line 56 - 58

**Comment by DrewBuan** [comment]
It's not a bug I wrote, I just made a guide

**Comment by astronomical-sandpaper** [comment]
For polymod's fix, i just reinstalled it using MasterEric's fork of it
