### ISSUE TITLE
lua.hpp error on Ubuntu

### ISSUE THREAD

**Issue by X4X5** [KadeDev/Funkin#2433]
In my attempt to build the Kade Engine for Linux, I keep running into this error. Any ideas for fixes?

```Error: In file included from ./src/LuaCharacter.cpp:5:
/home/x4x5/usr/linc_luajit/git//linc/linc_lua.h:12:10: fatal error: ../lib/Lua/src/lua.hpp: No such file or directory```

**Comment by Dobby233Liu** [comment]
https://github.com/KadeDev/Kade-Engine/issues/2366#issuecomment-931887693 ?

**Comment by X4X5** [comment]
Thanks, it built, but uh, was it supposed to build without an executable?
