### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by feder273** [KadeDev/Funkin#2446]
i have a problem and im scared that i will do something wrong this is what it shows up when i put lime test windows on my command window
![Screenshot (5)](https://user-images.githubusercontent.com/91979007/136072853-23aa3d20-32c7-44c7-a0c6-5347790db1b3.png)

**Comment by stephencomputer** [comment]
this is not a bug, you didn't put a } somewhere in your code where you were supposed to.

**Comment by feder273** [comment]
Oh thanks

**Comment by feder273** [comment]
> this is not a bug, you didn't put a } somewhere in your code where you were supposed to.

but the line 627 is not where my character stuff says
