### ISSUE TITLE
Bug Report: Pls i need help

### ISSUE THREAD

**Issue by Dusty1345** [KadeDev/Funkin#2448]
source/smTools/SMFile.hx:4: characters 8-22 : Type not found : haxe.Exception

can someone help me?

**Comment by notmagniill** [comment]
did you modify the source on smfile.hx?

**Comment by Dusty1345** [comment]
> did you modify the source on smfile.hx?

It's strange, the haxe.Exception is there, but the error is still happening, in other words i didn't have modified nothing
