### ISSUE TITLE
kade engine not open

### ISSUE THREAD

**Issue by random-dev1** [KadeDev/Funkin#2452]
when i build the game, it not open the game. When i try to open the exe file, it open the windows, loading to 20/21 and close the windows
can someone help me

https://user-images.githubusercontent.com/87105792/136309652-b2d1b7fe-fc47-4d47-bd38-508547a560a0.mp4

?

**Comment by DEV-idiotXD** [comment]
same

**Comment by random-dev1** [comment]
oh i found out just uninstall polymod and reinstall with this command ''haxelib git polymod https://github.com/MasterEric/polymod''

**Comment by DEV-idiotXD** [comment]
oh okay
