### ISSUE TITLE
Bug Report: Kade Engine crashes when compiling

### ISSUE THREAD

**Issue by BrandonHatesAnime** [KadeDev/Funkin#2458]
I downloaded a new Kade Engine source code (1.7). I didn't modify anything in the source code and just compiled it. When the loading screen gets to 21/21, instead of bringing you to the fnf startup it crashes. Can someone help or is this an issue?

**Comment by random-dev1** [comment]
same

**Comment by MaxxoWaton** [comment]
you need to uninstall polymod and reinstall with this command ''haxelib git polymod https://github.com/MasterEric/polymod''

**Comment by isakube** [comment]
https://github.com/KadeDev/Kade-Engine/issues/2459#issuecomment-937847044
