### ISSUE TITLE
Bug Report: newely compiled game crashes on start up

### ISSUE THREAD

**Issue by DEV-idiotXD** [KadeDev/Funkin#2459]
ok so when i just compiled the game to test if i got the correct libraries and yes i did when it was done exporting it opened then it shows the 1/21 assets loaded then when it reaches 21 it freezes then crashes please fix this i am developing a mod with one of my friends and i dont wanna have to install different libraries for a different version

-DEV-idiotXD

**Comment by isakube** [comment]
If you're compiling stable, go to TitleState and remove the line that inits Polymod. prs and shit were made and now it doesn't work.

**Comment by TheLeerName** [comment]
if you compiling master branch, go to Project.xml and remove the line with FEATURE_DISCORD, its not working for some reason.

**Comment by DEV-idiotXD** [comment]
> If you're compiling stable, go to TitleState and remove the line that inits Polymod. prs and shit were made and now it doesn't work.

ok lemme try it

**Comment by DEV-idiotXD** [comment]
> If you're compiling stable, go to TitleState and remove the line that inits Polymod. prs and shit were made and now it doesn't work.

how do you do that exactly? which line number is it...... im new to fnf modding
