### ISSUE TITLE
Bug Report: when i select my character in debug mode it just crashes

### ISSUE THREAD

**Issue by feder273** [KadeDev/Funkin#2476]
im sure i didnt mess up the code bc i copy and pasted the high effort ugh mod

**Comment by HastagGuigui** [comment]
> im sure i didnt mess up the code bc i copy and pasted the high effort ugh mod

high effort ugh mod uses FPS Plus, not kade engine, the syntax might be different

try copy and pasting other character codes from Character.hx

**Comment by feder273** [comment]
Oh ok then I will try other then
