### ISSUE TITLE
Enhancement: Old Editor

### ISSUE THREAD

**Issue by MaiBatchis** [KadeDev/Funkin#2479]
## What is your suggestion, and why should it be implemented?

Hi Kade!

Sorry to bother, but please, I beg you, bring back the old editor, I don't like the new one at all, and I'm not the only one, if you want you can "enchance" it a bit or whatever, but- Bring it back, please!

Thanks for reading!

**Comment by SomeKindofGamer** [comment]
or he could make it a option
