### ISSUE TITLE
The game keeps crashing after being built.

### ISSUE THREAD

**Issue by susbo1** [KadeDev/Funkin#2482]
I've looked for duplicates, I've reinstalled Kade Engine, and I deleted export and re-built it. I don't know what else to do

I am on windows 64bits

1.7

(There are different text for the other 6 errors)
cl.exe -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/lib/discord-rpc/include/ -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/lib/rapidjson/include/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdD:\vs\Kade-Engine-1.7\Kade-Engine-1.7\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_GC_BIG_BLOCKS(gc) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]

Whenever I try to load the game it crashes whenever it gets to 20. I'm not much of a coder, so I don't understand what's wrong. A bunch of code stuff things appear if it's under a compiling group

**Comment by feder273** [comment]
go to source and go to title state and delete line 57

**Comment by susbo1** [comment]
> go to source and go to title state and delete line 57

it didn't work, it still crashes once it gets to 20

**Comment by susbo1** [comment]
> go to source and go to title state and delete line 57

nvm it worked. thank you so much man
