### ISSUE TITLE
Can't compile please help

### ISSUE THREAD

**Issue by SomeKindofGamer** [KadeDev/Funkin#2485]
Recently got the 1.7.1 Pre-Release and i can't compile!
source/ModCore.hx:113: characters 48-71 : Type not found : polymod.FrameworkParams
source/Main.hx:19: lines 19-144 : Defined in this class
What do I do?

**Comment by LuigiSake** [comment]
got the same issue with 1.8 version of Kade Engine

"
BUILDING GAME
source/ModCore.hx:113: characters 48-71 : Type not found : polymod.FrameworkParams
source/Main.hx:20: lines 20-162 : ... Defined in this class
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

done.
Press any key to continue . . .
"

**Comment by LuigiSake** [comment]
i had the same issue with 1.8 but I did this and it fixed it :

"
haxelib remove polymod
haxelib git polymod https://github.com/MasterEric/polymod
"
