### ISSUE TITLE
i cant compile haxe

### ISSUE THREAD

**Issue by TyricSatyric** [KadeDev/Funkin#2487]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
this error exist but there is no god answer

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
use lime rebuild extension-webm windows
## Please describe your issue. Provide extensive detail and images if possible.
when i use that command appear this:
`Warning: Could not find Visual Studio 2017 VsDevCmd

Missing HXCPP_VARS

Error: Could not automatically setup MSVC`

**Comment by HastagGuigui** [comment]
you need to install the proper visual studio version

(from building.md)

> If you are planning to build for Windows, you also need to install **Visual Studio 2019**. While installing it, *don't click on any of the options to install workloads*. Instead, go to the **individual components** tab and choose the following:
>
> -   MSVC v142 - VS 2019 C++ x64/x86 build tools
> -   Windows SDK (10.0.17763.0)

**Comment by TyricSatyric** [comment]
> you need to install the proper visual studio version
> 
> (from building.md)
> 
> > If you are planning to build for Windows, you also need to install **Visual Studio 2019**. While installing it, _don't click on any of the options to install workloads_. Instead, go to the **individual components** tab and choose the following:
> > 
> > * MSVC v142 - VS 2019 C++ x64/x86 build tools
> > * Windows SDK (10.0.17763.0)

I have all of that installed
