### ISSUE TITLE
Bug Report:  Too Much time for lime test windows to compile (not first time)

### ISSUE THREAD

**Issue by bwkam** [KadeDev/Funkin#2489]
Hello, I recently started fnf modding, I built the game, and it worked fine, but there is that problem that when I edit something
just 2 things, it takes too much time to compile the next time., it took about 2 hours or more, so can I do to stop this problem,
because if that carried on, I won't be able to make a mod in a really huge time

Using Windows 10 64-bit

Using latest version of Kade engine (1.7)

**Comment by ReyingRexer** [comment]
What is your cpu clock speed

**Comment by bwkam** [comment]
![image](https://user-images.githubusercontent.com/91009118/136708880-c629bc3e-9888-47d9-875c-8d358c5c7126.png)

**Comment by ReyingRexer** [comment]
Yeah it is probably something to do with cpu idk
because compiling game uses a lot of cpu power

**Comment by bwkam** [comment]
alr I will try fixing that
