### ISSUE TITLE
Bug Report: source/PlayState.hx:392: characters 28-29 : Missing ;

### ISSUE THREAD

**Issue by feder273** [KadeDev/Funkin#2490]
here is the line 392 	defaultCamZoom = 0,9; and here is the entire line
![Screenshot (6)](https://user-images.githubusercontent.com/91979007/136700204-862083c6-2190-4d0d-b23d-4aca0669d78c.png)
![Screenshot (7)](https://user-images.githubusercontent.com/91979007/136700218-563ec059-edf6-484b-8f26-4187c1f75aff.png)

**Comment by feder273** [comment]
never mind i realised i put , instead of .

**Comment by feder273** [comment]
but now it says source/PlayState.hx:397: characters 5-7 : Missing ;

**Comment by IndigoVoidigo** [comment]
you forgot to put the ";" at the end of "bg.scrollFactor.set(0.9, 0.9)"

**Comment by feder273** [comment]
> you forgot to put the ";" at the end of "bg.scrollFactor.set(0.9, 0.9)"

Oh thank you
