### ISSUE TITLE
Bug Report: modcharts don't work

### ISSUE THREAD

**Issue by edgardeivis** [KadeDev/Funkin#2491]
modchart.lua files do nothing, i've made modcharts before, and even the tutorial one isn't working

**Comment by ghost** [comment]
1. Did You Install Everything For The Modcharts
2. Do You Have The Lua Extension Installed On Visual Studio Code?
3. Have You Tried Reinstalling The Source Code 
4. Put These Commands On Powershell Or windows Terminial
 haxelib remove linc_luajit
haxelib remove hxvm-luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

**Comment by edgardeivis** [comment]
I have downloaded the built game from GitHub

**Comment by Kade-github** [comment]
> modchart.lua files do nothing, i've made modcharts before, and even the tutorial one isn't working

Project.xml

You probably have something that is disabling 
![image](https://user-images.githubusercontent.com/26305836/137642200-90762e5e-dba5-4c71-8e5a-45979c47d22b.png)

this line of code, either u aren't on windows or you just removed it or never added it
