### ISSUE TITLE
Bug Report: game crashed

### ISSUE THREAD

**Issue by EvanGaming35** [KadeDev/Funkin#2498]
Im currently playing the 64bit
on windows 10

Version 1.7

Bug: well the game wont launch, after finish compiling and building the game. i opened the game. it was perfectly fine until when its loading 20/21. it crashed. i tried rebuilding the game and redoing all the steps and this keep happening. how do I solve it?

**Comment by Scoare** [comment]
this happened to me too o.o

**Comment by eutnet** [comment]
me too lol
rip kade engine

**Comment by cacahuwek** [comment]
same here

**Comment by MAUF443** [comment]
same here :(

**Comment by MAUF443** [comment]
the matter is in a broken exe file, download fnf KE from the link https://github.com/KadeDev/Kade-Engine/releases/tag/1.7 below and drag the exe file to the following path Kade-Engine-stable\export\release\windows\bin

**Comment by Kade-github** [comment]
^
