### ISSUE TITLE
error with lime test -debug

### ISSUE THREAD

**Issue by machonessiebaby** [KadeDev/Funkin#2510]
So I'm brand new to making mods in kade engine and as I was following a tutorial it said to use "lime test windows -debug" I tried this but "source/Character.hx:385: characters 4-8 : Expected }" appeared and nothing else
please let me know how to fix this
![e](https://user-images.githubusercontent.com/56323671/137408875-f5bacf2f-4a50-4fc4-8fe5-a24e37acceac.PNG)
also
i installed everything from the doc/MD file

**Comment by DrewBuan** [comment]
It could be two things,

1. You didn't install the linc_luajit branch:
You need to put in the following commands.

haxelib remove linc_luajit

haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit 0af04cd3a1


Or you could have installed the wrong Polymod:

The Polymod that is on the building.md document is disaffected on kade engine so you need to install mastereric's Polymod fork instead.

haxelib git polymod https://github.com/mastereric/polymod

**Comment by Dobby233Liu** [comment]
No, it's just their code

**Comment by machonessiebaby** [comment]
> No, it's just their code

im fairly new to this but
i dont think im gonna use kade anymore due the the huge amounts of coding required
