### ISSUE TITLE
kade you should add that

### ISSUE THREAD

**Issue by foxcool119** [KadeDev/Funkin#2512]
![image](https://user-images.githubusercontent.com/89747510/137503520-42288288-264d-4f0c-8f64-a50639a1306d.png)
the option on pause menu :D

**Comment by TheKitBoi** [comment]
bitch Kade isn’t updating Kade engine anymore

**Comment by isakube** [comment]
> bitch Kade isn’t updating Kade engine anymore

the last commit to master was 22 hours ago idiot

**Comment by Swapper1** [comment]
Is this present from FPS Plus?

**Comment by foxcool119** [comment]
@TheKitBoi  
![image](https://user-images.githubusercontent.com/89747510/137575887-24d449cd-3f51-4601-b2cc-9f5f3fa6ae3a.png)
then what is this

**Comment by ghost** [comment]
ye thekitboi is right kade engine 1.8 or 1.7.1 its not released yet

**Comment by foxcool119** [comment]
what do u mean  he said kade isn't updating kade engine anymore

**Comment by Burger-Gaming** [comment]
> bitch Kade isn’t updating Kade engine anymore

actually kade said he still was updating the engine

**Comment by foxcool119** [comment]
told ya

**Comment by foxcool119** [comment]
since kade has done updating kade engine 1.7.1 where is it ???

**Comment by TheLeerName** [comment]
> since kade has done updating kade engine 1.7.1 where is it ???

[master branch](https://github.com/KadeDev/Kade-Engine/tree/master) contains all changes in future version 1.7.1, something like beta version
and note, not all functions may work properly (for example, all sorts of unexpected crashes and errors)

**Comment by foxcool119** [comment]
![image](https://user-images.githubusercontent.com/89747510/137631589-da4dac7c-e6dc-42e7-ab50-4f8b53985cf7.png)
 i think i found it

**Comment by foxcool119** [comment]
![image](https://user-images.githubusercontent.com/89747510/137631703-91fdd2ad-b84f-4347-a69d-e34c66780188.png)
![image](https://user-images.githubusercontent.com/89747510/137631717-f65ae956-04a7-40ba-a75f-33c5ded113fe.png)
wait isnt that kade engine 1.7

**Comment by foxcool119** [comment]
![image](https://user-images.githubusercontent.com/89747510/137631982-0feda78d-6b50-45cc-82af-967834e66e84.png)
i thought the option looks like this  or he gonna add that soon

**Comment by Kade-github** [comment]
already done
