### ISSUE TITLE
Bug Report: Error with compiling game (reaching 21/21 and stopping)

### ISSUE THREAD

**Issue by JamJarIsDumb** [KadeDev/Funkin#2513]
when compiling my game, everything began fine, however when kade engine reached 21/21 assets loaded, the program stopped.

when i opened the debug in visual studio 2019, it gave me this message:
0x00007FF7F37657CF in Kade Engine.exe: 0xC0000005: Access violation reading location 0x0000000000000000
I've double checked everything was installed correctly, however i'm still unsure if this is a bug, or I am just missing something

please let me know if I can fix this
(screenshot of error message below):
![image](https://user-images.githubusercontent.com/92594242/137515834-9f4d5c13-9af0-4178-bc3c-b5934bb7dcb5.png)

**Comment by Xxtawoglinc6xX** [comment]
I also have that problem, when in starting kade engine it Just crashes

**Comment by bigbenster702** [comment]
Delete line 56, 57, and 58 on the file TitleState.hx Example of the line here: https://github.com/KadeDev/Kade-Engine/blob/30c630a7f67c7676d398f2e0e463d7fa07c72afb/source/TitleState.hx#L57

**Comment by JamJarIsDumb** [comment]
> Delete line 56, 57, and 58 on the file TitleState.hx Example of the line here:
> 
> https://github.com/KadeDev/Kade-Engine/blob/30c630a7f67c7676d398f2e0e463d7fa07c72afb/source/TitleState.hx#L57

this seems to have worked, thank you!

**Comment by Teaminate** [comment]
I have the same thing happening but it happens with my other projects that are Kade engine 1.5.4 is there a fix?
