### ISSUE TITLE
Pea Popper Fidget Toy

### ISSUE THREAD

**Issue by ghost** [KadeDev/Funkin#2518]
Watch this video of a pea popper fidget toy! https://youtu.be/Dg4ogREEzVs

**Comment by BiliousData** [comment]
This is not an issue.
Issues here are specifically for problems with Kade Engine.

**Comment by AstroOrbis** [comment]
this guy straight up begging for views x3

**Comment by EliteMasterEric** [comment]
Close this it's literal spam.
