### ISSUE TITLE
SEND ME THE LINK OF KADE ENGINE LATEST VERSION 

### ISSUE THREAD

**Issue by foxcool119** [KadeDev/Funkin#2532]

**Comment by foxcool119** [comment]
am annoying
am annoying
am annoying
am annoying
am annoying
am annoying
am annoying
am annoying
am annoying 
:                              D

**Comment by TheLeerName** [comment]
source code or compiled build?

**Comment by TheKitBoi** [comment]
Good luck getting hate lol

**Comment by TheKitBoi** [comment]
> am annoying
> am annoying
> am annoying
> am annoying
> am annoying
> am annoying
> am annoying
> am annoying
> am annoying
> : D

Good luck getting hate lol

**Comment by arceuss** [comment]
actions tab

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/actions/runs/1352207180
