### ISSUE TITLE
where tf do i disable the lane underlay or change the transparency of it

### ISSUE THREAD

**Issue by nahiassis** [KadeDev/Funkin#2533]

**Comment by EliteMasterEric** [comment]
Options > Apperance > Toggle Lane Underlay

**Comment by TheLeerName** [comment]
so far nowhere, [kade removed this line](https://github.com/KadeDev/Kade-Engine/commit/ababade33c46b5009a7d469a1c211da237185bcd#diff-236d47f7a4148da8570070ee0128a77bf36b3296d65e9841c43a07b389b31220) lol
![eteled lane underlay](https://user-images.githubusercontent.com/85291330/137645012-452d2e5b-8c6f-410d-b976-db7a272ec80f.png)

**Comment by Kade-github** [comment]
Options > Appearance > Lane Transparency > Press left until its 0

**Comment by Kade-github** [comment]
> so far nowhere, [kade removed this line](https://github.com/KadeDev/Kade-Engine/commit/ababade33c46b5009a7d469a1c211da237185bcd#diff-236d47f7a4148da8570070ee0128a77bf36b3296d65e9841c43a07b389b31220) lol ![eteled lane underlay](https://user-images.githubusercontent.com/85291330/137645012-452d2e5b-8c6f-410d-b976-db7a272ec80f.png)

fixed in https://github.com/KadeDev/Kade-Engine/commit/b7cecc8071908147892889185cdddbf09f52384e
