### ISSUE TITLE
Bug Report: Story Mode Week Songs freeze their cameras after the first song, but in Freeplay the cameras work just fine.

### ISSUE THREAD

**Issue by ramadoor** [KadeDev/Funkin#2538]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

I am on Windows 10, x64 bit operating system.

## What version of the game are you using? Look in the bottom left corner of the main menu.

I am currently using Kade Engine 1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

The bug occurs whenever you play a week. The first song plays normally, but every single song after it becomes bugged.

## Please describe your issue. Provide extensive detail and images if possible.
The bug goes like this: As soon as the "3, 2, 1, Go!" finishes playing, all the characters will play their idle once, and will then become stuck in their idle for the rest of the song. Gf will bop her head to the side once, then stays still with her head straight up for the rest of the song as well. 
Another thing is that the camera will no longer move. After the song starts playing, it will focus the camera to the character which is being focused on in the first section of the song's chart, and will stay stuck for the rest of the song. The picture below is what happened; bf and the opponent stayed still, gf's pose is now straight up, etc.
One thing to note is that the characters' poses work fine. Although that doesnt fix the problem. I also tried dying intentionally, resetting the song, but the problem persists.

The weirdest part about thi is that the songs work fine in Freeplay. Every song in freeplay works fine, the cameras move, bf and the opponent do their poses, gf bops her head, the usual.

I have already compared the charts and nothing seems to be off about the charts.
![bruhskito](https://user-images.githubusercontent.com/81607123/137717519-82a8b00b-8006-4732-ba9a-94285a6b4755.png)

**Comment by ishsharm0** [comment]
I can vouch for this bug, I've been experiencing it as well (using last 1.7 release/SC).

**Comment by ramadoor** [comment]
have you found any solutions yet?

**Comment by ramadoor** [comment]
https://drive.google.com/file/d/1Fr4MUfnHhV_mgV-FdjJbrYV8ly2dcL7x/view?usp=sharing

here is a video showcasing the bug,

**Comment by ishsharm0** [comment]
has been fixed in 1.8, you can close it now

**Comment by ghost** [comment]
Is there a solution for 1.7?

**Comment by ishsharm0** [comment]
> Is there a solution for 1.7?

i would recommend you just update your code to 1.8 because 1.7 isn't updated anymore, that's how old versions work
