### ISSUE TITLE
Bug Report: The game crashes instantly after loading.

### ISSUE THREAD

**Issue by AubreyTheSilly** [KadeDev/Funkin#2556]
I'm on Mac, and on the loading screen once it got to 21/21 the game just closed. I have no idea what is happening. I'm currently on Kade Engine 1.7.

**Comment by TheGamingCat89** [comment]
inside command prompt
haxelib remove polymod
then run
haxelib git polymod https://github.com/MasterEric/polymod
it might work but idk about mac

**Comment by AubreyTheSilly** [comment]
Thanks, I will try it.
