### ISSUE TITLE
Pause Bug On KE 1.8

### ISSUE THREAD

**Issue by lxcianitoc0des** [KadeDev/Funkin#2575]
I Was Playing KE 1.8 And When I Load Any Song It Pauses And I Can't Resume Because It Pauses Again.
A Text Appears Saying "hello chat" On The Pause Screen

**Comment by GamingInfinite** [comment]
This happened when I had a controller plugged in.  I would try unplugging any controllers you have plugged in because it kept thinking I was hitting the pause button on my controller.

**Comment by glowsoony** [comment]
when i paused my game crashed for no reason i used nothing to make it crash.
