### ISSUE TITLE
Bug Report: 1.8 Arrows are broken on MacOS (compiled)

### ISSUE THREAD

**Issue by test672issue** [KadeDev/Funkin#2605]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
maybe
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
macOS
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.8
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Open the app, press enter, go to freeplay, select any song in freeplay, and that's where the arrows are
## Please describe your issue. Provide extensive detail and images if possible.
When I go to any song in freeplay, the messed-up arrows appear

**Comment by tate-b** [comment]
I have this issue too

**Comment by leobro1106** [comment]
me three
