### ISSUE TITLE
Why it stops running when click "reload audio"?

### ISSUE THREAD

**Issue by zwl1619** [KadeDev/Funkin#2610]
I am using 1.8-stable,
I added a song following this video: https://www.youtube.com/watch?v=Y5-6wbwrWXQ
and the song I added is named "happy",
first,I put the audio files into `Kade-Engine-stable\assets\songs`,
then add `happy:dad:7` into `Kade-Engine-stable\assets\preload\data\freeplaySonglist.txt`,
and then compile,
then press 7 , 
then modify song name ,and press "reload audio", it stops running.

![Snipaste_2021-10-26_17-05-41](https://user-images.githubusercontent.com/13177997/138847439-1a9ed8ee-a922-475d-92d1-662c0a65d59d.png)

What should I do?

**Comment by ahhhgghhhhhvh** [comment]
same problem dont know why
