### ISSUE TITLE
Bug Report: Sicks not reseting

### ISSUE THREAD

**Issue by Jotaro-Gaming** [KadeDev/Funkin#2623]
if you play a song and reload it everything resets 
well not everything sicks dont reset for some reason 
(accuracy is what im talking about)

**Comment by Jotaro-Gaming** [comment]
wtf the sicks stay even if you change the song

**Comment by Jotaro-Gaming** [comment]
my version is 1.8 btw

**Comment by TheLeerName** [comment]
fixed in [here](https://github.com/KadeDev/Kade-Engine/commit/50d60bed8f1fe32c5bee56fdf49a7f7ca2abe5a4), by voting on twitter there will be 1.8.1 version

**Comment by Jotaro-Gaming** [comment]
kay
