### ISSUE TITLE
Bug Report: idk if this is a bug or its just me

### ISSUE THREAD

**Issue by SomeKindofGamer** [KadeDev/Funkin#2634]
Alright look,
Ever since I started compiling and working on a Mod which was made on KE 1.8
any single mod/compile which was on KE 1.5.x just doesn't work anymore
it just crashes
I made this huge mod pack which was built on KE 1.5.2 and it was working fine ever since i started compiling 1.8
then when i compile 1.5.2 it just crashes now.

It happens to every single one
even my glitch engine (glitch engine is KE 1.5.2 just rebranded and new stuff)

https://user-images.githubusercontent.com/84479483/139351148-852e1a41-3935-4d2c-80cb-2580c766ad26.mp4

**Comment by SomeKindofGamer** [comment]
did debug mode, mod pack still crashes but glitch engine brings up a null object reference
still dont know what modpack is doing
but glitch engine is fixed now

**Comment by sebvilyt** [comment]
bro same happens to me and idk how to fix it

**Comment by skedgyedgy** [comment]
-- did you close this because you fixed it? if so how did you fix it?
