### ISSUE TITLE
Kade, if you are reading this... this is just a request.

### ISSUE THREAD

**Issue by NotSorena** [KadeDev/Funkin#2652]
I know you stopped updating this but...
Can I have source code of a Kade Engine 1.8 version that is able to compile to HTML5?

**Comment by Dobby233Liu** [comment]
literally download the stable branch lol https://codeload.github.com/KadeDev/Kade-Engine/zip/stable

**Comment by NotSorena** [comment]
ok lol

**Comment by NotSorena** [comment]
IT DOESNT FUCKING WORKKKKKKKKKKKKKKKK

**Comment by NotSorena** [comment]
I SAID A KADE ENGINE 1.8 VERSION THAT CAN COMPILE TO HTML5 AND ACTUALLY WORK
NOT JUST KADE ENGINE 1.8

**Comment by Dobby233Liu** [comment]
didn't MasterEric fix it or smth

**Comment by Dobby233Liu** [comment]
better try building it if you didn't (like I thought)

**Comment by NotSorena** [comment]
i did build it
cmd.exe
lime build html5
only loads the haxeflixel screen and nothing else
