### ISSUE TITLE
Gf animation not working

### ISSUE THREAD

**Issue by XxYourMomxX** [KadeDev/Funkin#2666]
Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
If you are playing a downloaded version of the game, what operating system are you using?
Windows (x86), Windows (x86_64), Linux, or macOS? Specify below.

Windows x86_64

What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.4.2
Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
idk how to recreate it
Please describe your issue. Provide extensive detail and images if possible.
When I load into a song while the 3 2 1 go start its normal the after it finishes the gf justs keep repeating the danceLeft animation

https://user-images.githubusercontent.com/85022591/139757055-bb122465-7bdf-4949-ab1a-bcb7c8f21aca.mp4

**Comment by RagdollClash** [comment]
Wouldn't it be better to just use 1.8's modcore feature?

**Comment by XxYourMomxX** [comment]
> Wouldn't it be better to just use 1.8's modcore feature?

it would but most mods aren't compatible with it bc every update something changes

**Comment by FuseIsHere813** [comment]
Your version is outdated, try using 1.8 of KE to see if the bugs go away.

**Comment by XxYourMomxX** [comment]
> Your version is outdated, try using 1.8 of KE to see if the bugs go away.

its alright i found a solution for my self
I replaced gf dance animation code with this 

if (animation.curAnim.name != 'danceRight')
					{
						danced = !danced;

						if (danced)
							playAnim('danceRight');
						else
							playAnim('danceLeft');
					}
					else if (animation.curAnim.name != 'danceLeft')
					{
						danced = !danced;

						if (danced)
							playAnim('danceLeft');
						else
							playAnim('danceRight');
					}
Edit: Gf did the animations twice but i used two lines of code for ke 1.8 

else if (curCharacter == 'gf' || curCharacter == 'spooky')
				dadVar = 4.1; // fix double dances

and 

if (!animation.curAnim.name.startsWith('hair') && !animation.curAnim.name.startsWith('sing'))
					{
						danced = !danced;

						if (danced)
							playAnim('danceRight');
						else
							playAnim('danceLeft');
					}
and it fixed
