### ISSUE TITLE
Bug Report: how do i fix this?

### ISSUE THREAD

**Issue by ghost** [KadeDev/Funkin#2675]
obj\msvc1964-nc\4d3a1b16_NativeOpenGLRenderContext.obj : fatal error LNK1136: invalid or corrupt file 
how do i fix this  
im on windows 64 bit

**Comment by stilic** [comment]
Just delete the mentionned file (in export folder) and recompile

**Comment by ghost** [comment]
where is the mention file in the export folder?

**Comment by stilic** [comment]
Check the `export\release\windows` folder. Maybe you will found it here?

**Comment by ghost** [comment]
can you add me on discord @Stilic

**Comment by VojPlaUwU** [comment]
I have the same problem :/ but when Im gonna recompile the file, Its still giving me this error

**Comment by notmagniill** [comment]
just go to `export\release\windows\obj\msvc1964-n` and then delete the `4d3a1b16_NativeOpenGLRenderContext.obj`

**Comment by ghost** [comment]
nevermind i fixed it

**Comment by stilic** [comment]
ok so close this issue
