### ISSUE TITLE
Bug Report: sick notes accumulating

### ISSUE THREAD

**Issue by v0id96** [KadeDev/Funkin#2695]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.8

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
basically, playing normally

## Please describe your issue. Provide extensive detail and images if possible.
sick note hits are accumulating
![image](https://user-images.githubusercontent.com/72328566/140676041-0bf55577-a5a8-45e6-a543-13280d1e7f3a.png)

**Comment by GamingInfinite** [comment]
Next update (or any version that is built currently) will have fixed this issue, as Kade as implemented the fix for this (check commits).  I'd recommend just waiting for next update but either way this issue has been fixed
