### ISSUE TITLE
Help me :<

### ISSUE THREAD

**Issue by Syro-nuke** [KadeDev/Funkin#2790]
How i install VS 2019 (or 2017) in 2022? :<

**Comment by fledermaus101** [comment]
https://visualstudio.microsoft.com/vs/older-downloads/
and download and install the version you want

**Comment by Syro-nuke** [comment]
> https://visualstudio.microsoft.com/vs/older-downloads/ and download and install the version you want

I can't, because I must pay to get VS 2019 version

**Comment by Syro-nuke** [comment]
> > https://visualstudio.microsoft.com/vs/older-downloads/ and download and install the version you want
> 
> I can't, because I must pay to get VS 2019 version

"Visual Studio 2019 and other products
To download any product from the following list, click the download button and sign in with your Visual Studio Subscription account when prompted. If you don't have Visual Studio Subscription, you can create a free one by clicking "Create a new Microsoft account" on the login page.

Visual Studio Professional 2019; Visual Studio Enterprise 2019;

Build Tools for Visual Studio 2019

Visual Studio Team Explorer 2019

Agents for Visual Studio 2019

Standalone IntelliTrace Collector for Visual Studio 2019

Performance Tools for Visual Studio 2019

Remote Tools for Visual Studio 2019

Microsoft Visual C++ Redistributable Packages for Visual Studio 2019", this what it says when i open the tab to download it

**Comment by fledermaus101** [comment]
Oh sorry didn't actually check if it worked
Here this time I tested it:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

**Comment by Syro-nuke** [comment]
> Oh sorry didn't actually check if it worked Here this time I tested it: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

I'll try later, I'll let you know as soon as it works.

**Comment by Syro-nuke** [comment]
> Oh sorry didn't actually check if it worked Here this time I tested it: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

well i took a quick look at the website and... it contains the download there, thanks for helping me

**Comment by fledermaus101** [comment]
Can you close the issue?
