### ISSUE TITLE
running lime test windows spits out an error message

### ISSUE THREAD

**Issue by Derussianboi** [KadeDev/Funkin#2801]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
i followed everyting up to the error
## Please describe your issue. Provide extensive detail and images if possible.
Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist

**Comment by AubreyTheSilly** [comment]
Have you installed extension-webm?

**Comment by Derussianboi** [comment]
i dont know what that is

**Comment by AubreyTheSilly** [comment]
Type 'haxelib git extension-web https://github.com/KadeDev/extension-webm'. Then type 'lime rebuild extension-webm windows'. Then try building the game again.

**Comment by Derussianboi** [comment]
that fixed it 
thanks

**Comment by AubreyTheSilly** [comment]
np
