### ISSUE TITLE
Compiling on 1.8, 1.7 and 1.6.

### ISSUE THREAD

**Issue by Superyoshi94** [KadeDev/Funkin#2815]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
There are a lot of closed issues about this, but nothing anybody has said in the closed issues works for me.
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (x64)
## What version of the game are you using? Look in the bottom left corner of the main menu.
This happens in 1.8, 1.7 and 1.6.
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
All I have to do is run "lime test windows" or "lime build windows".
## Please describe your issue. Provide extensive detail and images if possible.
I have been trying and checking on every single issue, nothing they have said worked. Basically when you do "lime test windows" this happens.
Log:
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/WebmHandler.hx:32: characters 10-26 : Not enough arguments, expected io:webm.WebmIo, soundEnabled:Bool
source/WebmHandler.hx:33: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:96: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:102: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:53: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:119: characters 8-19 : webm.WebmPlayer has no field removePause

This is a very common problem, but nothing in the closed or open issues work.

**Comment by Superyoshi94** [comment]
Also the only hope I have is on 1.5.2. (When compiling) I might go back to 1.5.2.

**Comment by MarkimusZer0** [comment]
it seems like something with the webm handler, do you have kade's extension-webm library?

**Comment by Superyoshi94** [comment]
> it seems like something with the webm handler, do you have kade's extension-webm library?

I do have the extension-webm library, but if you are talking about Kade's version, I don't.

**Comment by Superyoshi94** [comment]
> it seems like something with the webm handler, do you have kade's extension-webm library?

I will try to get that version and use that.

**Comment by Superyoshi94** [comment]
That didn't work.

**Comment by MarkimusZer0** [comment]
i think you should try removing the one you got and kade and following the build instructions on KE's master branch, had worked for me

**Comment by Superyoshi94** [comment]
> i think you should try removing the one you got and kade and following the build instructions on KE's master branch, had worked for me

Thank you! This works completely fine.

**Comment by Superyoshi94** [comment]
https://user-images.githubusercontent.com/82662993/150626701-d6c51304-06c0-4e87-b618-0fdfa32b22e6.mp4

wait what the fuck

**Comment by Sylveondev** [comment]
I compiled KE 1.6
I should've done 1.6.2 instead but I didn't feel like porting my code over
