### ISSUE TITLE
Saving charts

### ISSUE THREAD

**Issue by Superyoshi94** [KadeDev/Funkin#2822]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Building for (x86_64)
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.8
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Save a chart with notes on bf's side that were copied, all of his notes will be deleted
## Please describe your issue. Provide extensive detail and images if possible.
If you go into the charter, copy charted notes on bf's side, and then save or play the chart, all of the notes of bf's side will be deleted.

**Comment by Superyoshi94** [comment]
Nevermind, this only happens sometimes

**Comment by Superyoshi94** [comment]
Oh god nevermind again.

**Comment by Superyoshi94** [comment]
Never get back into the chart, everything will be gone.

**Comment by Superyoshi94** [comment]
Found a solution, chart it with psych engine.

**Comment by Superyoshi94** [comment]
No that makes it broken.

**Comment by Superyoshi94** [comment]
I found a solution, arrowvortex.

**Comment by Sylveondev** [comment]
😐

**Comment by JorosTheModderPH** [comment]
Lol

**Comment by isakube** [comment]
🤨

**Comment by Sylveondev** [comment]
🤔

**Comment by Sylveondev** [comment]
Are you using the extra keys mod?
