### ISSUE TITLE
Bug Report: The Engine Spams Guide Button (KE 1.8)

### ISSUE THREAD

**Issue by KiraBytesGit** [KadeDev/Funkin#2848]
This Bug Makes The Game Unplayable
Here's The Video: https://youtu.be/7sNAWjQzTxA

**Comment by Knuxy03** [comment]
nevermind, i just forgot to disconnecting my ps2 controller

**Comment by KiraBytesGit** [comment]
nevermind, i just forgot to disconnecting my ps2 controller
