### ISSUE TITLE
Bug Report: Polymod giving errors when building all of a sudden

### ISSUE THREAD

**Issue by AdmiralKirby** [KadeDev/Funkin#2851]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
Any version
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
lime test windows
## Please describe your issue. Provide extensive detail and images if possible.
Every time I try to build the game Polymod seems not to cooperate at all. I was just able to make it run earlier today but now it just says there is these errors, what am I doing wrong
![Capture](https://user-images.githubusercontent.com/36349220/153793582-44190c31-f329-41f7-820e-a54253f836c1.PNG)
?

**Comment by Sylveondev** [comment]
A Polymod update broke every fnf build. Use this fork instead. 
https://github.com/MasterEric/polymod.git

```haxelib git polymod https://github.com/MasterEric/polymod.git```

Kade should pin this since a lot of people will experience this issue if they don't use the fork.

**Comment by AdmiralKirby** [comment]
> A Polymod update broke every fnf build. Use this fork instead. https://github.com/MasterEric/polymod.git
> 
> `haxelib git polymod https://github.com/MasterEric/polymod.git`
> 
> Kade should pin this since a lot of people will experience this issue if they don't use the fork.

Thanks a lot, this just fixed everything.
