### ISSUE TITLE
i can't build kade engine (solved)

### ISSUE THREAD

**Issue by ADA-Funni** [KadeDev/Funkin#2861]
when i try it says this: C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 35-48 : openfl.utils.IAssetCache has no field getBitmapKeys (Suggestion: getBitmapData)
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 15-50 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 35-46 : openfl.utils.IAssetCache has no field getFontKeys
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 15-48 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 35-47 : openfl.utils.IAssetCache has no field getSoundKeys
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 15-49 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/Polymod.hx:483: characters 80-81 : Missing ;
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/Polymod.hx:483: characters 80-81 : For function argument 'message'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/Polymod.hx:494: characters 82-83 : Missing ;
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/Polymod.hx:494: characters 82-83 : For function argument 'message'
**It doesn't do this when i build psych engine, what do i do**

**Comment by ADA-Funni** [comment]
it does the same thing on regular fnf

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
IT JUST A NORMAL THING

**Comment by oof-plays-yt** [comment]
> 

how do i fix it

**Comment by ADA-Funni** [comment]
> IT JUST A NORMAL THING

then how do i fix it

**Comment by ADA-Funni** [comment]
actually give me an answer as to how to fix it, it won't let me compile AT ALL.

**Comment by BoloVEVO** [comment]
Go to titleState.hx and comment this line like this. Polymod is broken in old KE versions. Ignore the Gamejolt thing lol.
![image](https://user-images.githubusercontent.com/88955176/155866736-96a8acbe-2fe9-4304-8fe2-fc8c3dcf96b6.png)
