### ISSUE TITLE
kade engine compilation problem

### ISSUE THREAD

**Issue by leesslk** [KadeDev/Funkin#2876]
first of all... i'm brazilian and i'm using google translator

and secondly

when I try to compile kade engine I get an error like this: C:/HaxeToolkit/haxe/lib/polymod/git/polymod/fs/PolymodFileSystem.hx:18: characters 18-20 : Expected )

![Screenshot_4](https://user-images.githubusercontent.com/100552511/155927850-926b1019-9161-47af-8a85-0f87b2195445.png)

I'm new here and

please help me

**Comment by AwesomeWithRex** [comment]
Go to https://kadedev.github.io/Kade-Engine/building and do all of that, this worked for me
