### ISSUE TITLE
Bug Report: Compile issue

### ISSUE THREAD

**Issue by suskas** [KadeDev/Funkin#2879]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/fs/PolymodFileSystem.hx:18: characters 18-20 : Expected ) ---This is fixed now

C:/HaxeToolkit/haxe/lib/polymod/1,5,2/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected ) ---This is now a new one how can i fix this?

This happens everytime when i compile kade engine please help

**Comment by khmanbip** [comment]
same :/

**Comment by test0082345** [comment]
so glad to see that i am not the only person with this problem

**Comment by test0082345** [comment]
i found out how to fix it run the haxe installation again and go in cmd as admin run

haxelib update

hope this fixed your problem


if you have any more problems i have a discord Twonog#8820

**Comment by suskas** [comment]
i still have the same issue

**Comment by suskas** [comment]
nvm i fixed it i had to delete the code

**Comment by BoagerEpic301** [comment]
> nvm i fixed it i had to delete the code

what code

**Comment by FNF-BOI** [comment]
Pls help I have this problem C:/HaxeToolkit/haxe/lib/polymod/1,5,2/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected )
