### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by gabi123qwqwqwqwqwqwq** [KadeDev/Funkin#2886]
when i compile the game appears : 
C:/HaxeToolkit/haxe/lib/polymod/1,5,2/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected ) can someone help me?

**Comment by NK-523** [comment]
I remember having this issue, I don't remember how I fixed it though. It was like 5-6 months ago. someone else has the same issue here: #2877 

Hope something here helps, I don't know if it will though.

**Comment by NK-523** [comment]
Also, if that doesn't work, try looking through the closed issues, something there might help too.

**Comment by SSJDeathSpawn** [comment]
I was able to fix it by replacing all occurrences (only 2) of 'is' in the file with '==' (C:/HaxeToolkit/haxe/lib/polymod/1,5,2/polymod/fs/PolymodFileSystem.hx in your case). I suggest trying the same

**Comment by Benby3** [comment]
go to (example): C:\HaxeToolkit and delete everything. after this reinstall everything (EVERYTHING THAT THE TUTORIAL ASK TO DOWNLOAD)

**Comment by gabi123qwqwqwqwqwqwq** [comment]
thanks it really helped:)
