### ISSUE TITLE
Bug Report: Uncaught TypeError: s is undefined in loadKeyBinds under HTML5 build.

### ISSUE THREAD

**Issue by eM-Krow** [KadeDev/Funkin#2913]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
N/A

## What version of the game are you using? Look in the bottom left corner of the main menu.
Can't get past loading screen, using latest v1.8 Kade Engine

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Build latest in html5

## Please describe your issue. Provide extensive detail and images if possible.
```Uncaught TypeError: s is undefined
    loadKeyBinds https://examplesitename.com/files/kade1.8/Kade Engine.js:11509
    setKeyboardScheme https://examplesitename.com/files/kade1.8/Kade Engine.js:10207
    Controls https://examplesitename.com/files/kade1.8/Kade Engine.js:10197
    PlayerSettings https://examplesitename.com/files/kade1.8/Kade Engine.js:24791
    init https://examplesitename.com/files/kade1.8/Kade Engine.js:24797
    create https://examplesitename.com/files/kade1.8/Kade Engine.js:27331
    switchState https://examplesitename.com/files/kade1.8/Kade Engine.js:31828
    create https://examplesitename.com/files/kade1.8/Kade Engine.js:31728
    __dispatchEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4908
    __dispatchEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:5356
    __dispatchWithCapture https://examplesitename.com/files/kade1.8/Kade Engine.js:5396
    addChildAt https://examplesitename.com/files/kade1.8/Kade Engine.js:6083
    addChild https://examplesitename.com/files/kade1.8/Kade Engine.js:6034
    setupGame https://examplesitename.com/files/kade1.8/Kade Engine.js:6600
    init https://examplesitename.com/files/kade1.8/Kade Engine.js:6581
    __dispatchEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4908
    __dispatchEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:5356
    __dispatchWithCapture https://examplesitename.com/files/kade1.8/Kade Engine.js:5396
    addChildAt https://examplesitename.com/files/kade1.8/Kade Engine.js:6083
    addChild https://examplesitename.com/files/kade1.8/Kade Engine.js:6034
    main https://examplesitename.com/files/kade1.8/Kade Engine.js:6557
    start https://examplesitename.com/files/kade1.8/Kade Engine.js:4748
    tmp https://examplesitename.com/files/kade1.8/Kade Engine.js:4726
    dispatch https://examplesitename.com/files/kade1.8/Kade Engine.js:70416
    display_onUnload https://examplesitename.com/files/kade1.8/Kade Engine.js:78856
    __dispatchEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4908
    __dispatchEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:5356
    __dispatchWithCapture https://examplesitename.com/files/kade1.8/Kade Engine.js:5396
    dispatchEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:5283
    onLoaded https://examplesitename.com/files/kade1.8/Kade Engine.js:57369
    onEnterFrame https://examplesitename.com/files/kade1.8/Kade Engine.js:57432
    __dispatchEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4908
    __dispatch https://examplesitename.com/files/kade1.8/Kade Engine.js:5344
    __broadcastEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:79759
    __onLimeRender https://examplesitename.com/files/kade1.8/Kade Engine.js:80786
    dispatch https://examplesitename.com/files/kade1.8/Kade Engine.js:70477
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4225
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    handleApplicationEvent https://examplesitename.com/files/kade1.8/Kade Engine.js:4235
    exec https://examplesitename.com/files/kade1.8/Kade Engine.js:4201
    exec https://examplesitename.com/files/kade1.8/Kade Engine.js:4477
    create https://examplesitename.com/files/kade1.8/Kade Engine.js:4744
    embed https://examplesitename.com/files/kade1.8/Kade Engine.js:72664
    embed https://examplesitename.com/files/kade1.8/Kade Engine.js:103738
    <anonymous> https://examplesitename.com/files/kade1.8/:75```
    
    Probably related to latest commit, also domain was expunged.

**Comment by eM-Krow** [comment]
Oh forgot to include the cmdlet output:
```S:\Downloads\Kade-Engine-1.8\Kade-Engine>lime build html5
source/DiffOverview.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/GameplayCustomizeState.hx:81: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:437: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/Replay.hx:103: characters 16-35 : Warning : Usage of this field is deprecated
source/StageDebugState.hx:104: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead```

**Comment by BoloVEVO** [comment]
KadeDev doesn't mantain Kade Engine anymore and html5 build is broken. I tried to fix it but it just mess it more. Sorry

**Comment by BoloVEVO** [comment]
Ok I managed to run KE 1.8 HTML5 build. It's because a undefined string error inside Controls.hx. Just make an Std.string inside each FlxG.save.data.bind and it will run HTML5. Only Main Menu, Story menu and Option menu work fine. Freeplay Menu and PlayState are still broken due to String functions that HTML5 doesn't support.
![image](https://user-images.githubusercontent.com/88955176/167165515-0b8bb032-f819-40f7-a52e-afa3d4291399.png)

**Comment by eM-Krow** [comment]
Huh seems like the whole thing is a mess then. Yeesh. Some progress at least.

**Comment by BoloVEVO** [comment]
> Huh seems like the whole thing is a mess then. Yeesh. Some progress at least.

Rn I've just fixed the entire latest HTML5 build [itch.io Browser version](https://bolo24.itch.io/kade-engine-181) or [mirror](https://v6p9d9t4.ssl.hwcdn.net/html/5778995/index.html ). Also check my Kade Engine fork [here](https://github.com/BoloVEVO/Kade-Engine). Same compile instructions. pog.

**Comment by eM-Krow** [comment]
> > Huh seems like the whole thing is a mess then. Yeesh. Some progress at least.
> 
> Rn I've just fixed the entire latest HTML5 build [itch.io Browser version](https://bolo24.itch.io/kade-engine-181) or [mirror](https://v6p9d9t4.ssl.hwcdn.net/html/5778995/index.html). Also check my Kade Engine fork [here](https://github.com/BoloVEVO/Kade-Engine). Same compile instructions. pog.

Seems to be working mostly, though some minor issues like no music besides last played at the menus and eval chart being broken but basically all works. Appreciate the work you put in. (Also yikes on these inputs. Hopefully Average4K gets a nice input system like Etterna).
![image](https://user-images.githubusercontent.com/87371945/168315651-04d7f21d-21ad-402c-b2ed-2de8a79f1ada.png)

Also just a note with your fork, it does require `hxcpp-debug-server` to be installed to build which differs from the main repo. Just thought I'd mention it.

**Comment by BoloVEVO** [comment]
> eval c

Thanks, it's still in progress to fix all the bugs but it's kinda stable, more than Camellia 2.0 KE. Also playback rate in browser build it's disable because Flixel  does not support pitch shifting in html5 target, otherwise the music will sound very bad. Speaking about the hxcpp-debug-server yeah I forgot about that, I included to the project for debugging the game correctly and trace errors and nulls references that crashes the game. About the input yeah, it's kinda meh I don't feel comfortable with Psych Engine input, so I prefer this input instead.
